# Generated by Django 5.1 on 2025-11-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='nssf_number',
        ),
    ]
