# Generated by Django 5.2.11 on 2026-03-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
    ]
