# Generated by Django 5.1 on 2025-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Phase 1.6: Student portal access'),
        ),
    ]
