# Generated by Django 5.1 on 2025-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='tin_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
