# Generated by Django 5.2.11 on 2026-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_drop_token_blacklist_user_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                    ("accountant", "Accountant"),
                ],
                help_text="Currently active role for users with multiple roles",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_inspector",
            field=models.BooleanField(
                default=False,
                help_text="Public-schema only. Cross-tenant read-only access. Not part of school-level active_role switching.",
            ),
        ),
    ]
