# Generated by Django 5.2.11 on 2026-02-20 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "active_year",
                    models.BooleanField(
                        help_text="DANGER!! This is the current school year. There can only be one and setting this will remove it from other years. If you want to change the active year, click Admin, Change School Year."
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("picture", models.ImageField(upload_to="carousel")),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ("day",),
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="articles"),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="DANGER..!!!! If marked, this will be the default School Information System Wide...",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=250)),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("boarding school", "boarding school"),
                            ("day school", "day school"),
                            ("boarding-day school", "boarding-day school"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "students_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Boys School", "Boys School"),
                            ("Girl School", "Girl School"),
                            ("Mixed", "Mixed"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        blank=True,
                        choices=[("Government", "Government"), ("Private", "Private")],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("mission", models.TextField(blank=True, null=True)),
                ("vision", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "school_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "school_logo",
                    models.ImageField(blank=True, null=True, upload_to="school_info"),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="administrat_name_c974a6_idx"),
                    models.Index(
                        fields=["active"], name="administrat_active_1f2ae9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "default_term_fee",
                    models.DecimalField(
                        decimal_places=2, default=312500, max_digits=10
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="administration.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the event (e.g., Midterm Exams, Eid Holiday)",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("exam", "Examination Period"),
                            ("graduation", "Graduation Day"),
                            ("holiday", "Holiday"),
                            ("leave", "Student Leave"),
                            ("other", "Other Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional details about the event"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="The term this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ua",
                    models.CharField(
                        help_text="User agent. We can use this to determine operating system and browser in use.",
                        max_length=2000,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField()),
                ("usage", models.CharField(max_length=255)),
                (
                    "login",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["login"], name="administrat_login_i_b9be62_idx"
                    ),
                    models.Index(fields=["date"], name="administrat_date_0e2943_idx"),
                ],
            },
        ),
    ]
