# Generated by Django 5.2.11 on 2026-07-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_remove_term_default_term_fee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ("start_date",)},
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("name", "academic_year")},
        ),
    ]
