# Generated by Django 5.2.11 on 2026-07-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_term_options_alter_term_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevent',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='The academic year this event belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='administration.academicyear'),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Optional term this event belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='administration.term'),
        ),
    ]
