# Generated by Django 5.1 on 2025-06-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_term_default_term_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event (e.g., Midterm Exams, Eid Holiday)', max_length=255)),
                ('event_type', models.CharField(choices=[('exam', 'Examination Period'), ('graduation', 'Graduation Day'), ('holiday', 'Holiday'), ('leave', 'Student Leave'), ('other', 'Other Event')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional details about the event')),
                ('term', models.ForeignKey(help_text='The term this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='administration.term')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
