# Generated by Django 5.1 on 2025-06-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_schoolevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='graduation_date',
        ),
    ]
