# Generated by Django 5.1 on 2025-11-23 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.CharField(blank=True, max_length=300)),
                ('school_city', models.CharField(blank=True, max_length=100)),
                ('school_state', models.CharField(blank=True, max_length=100)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('academic_year_start_month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=9, help_text='Month when academic year starts (1=January, 12=December)')),
                ('terms_per_year', models.IntegerField(choices=[(2, '2 Terms'), (3, '3 Terms'), (4, '4 Terms (Quarters)')], default=3, help_text='Number of terms per academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
