# Generated by Django 5.2.11 on 2026-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalIDRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=20)),
                (
                    "unique_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "current_schema",
                    models.CharField(blank=True, db_index=True, max_length=63),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "unique_id"],
                        name="core_global_entity__d07ef5_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "current_schema"],
                        name="core_global_entity__5c4db5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=50)),
                ("entity_type", models.CharField(max_length=20)),
                ("from_schema", models.CharField(blank=True, max_length=63)),
                ("to_schema", models.CharField(max_length=63)),
                ("person_name", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("transferred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-transferred_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_id", "transferred_at"],
                        name="core_transf_entity__fc573b_idx",
                    )
                ],
            },
        ),
    ]
