# Generated by Django 5.2.11 on 2026-06-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_globalidregistry_add_identity_fields_transferlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="globalidregistry",
            new_name="core_global_entity__5c4db5_idx",
            old_name="core_global_entity_schema_idx",
        ),
        migrations.RenameIndex(
            model_name="transferlog",
            new_name="core_transf_entity__fc573b_idx",
            old_name="core_transfer_entity_idx",
        ),
    ]
