# Generated by Django 5.2.11 on 2026-02-20 10:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("administration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbr", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Payment Categories",
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("Tuition", "Tuition"),
                            ("Transport", "Transport"),
                            ("Meals", "Meals"),
                            ("Books", "Books"),
                            ("Uniform", "Uniform"),
                            ("Other", "Other"),
                        ],
                        default="Tuition",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard amount for this fee",
                        max_digits=10,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Mandatory fees are auto-assigned to all applicable students",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Due date for this fee", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="administration.academicyear",
                    ),
                ),
                (
                    "class_levels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave blank to apply to all class levels",
                        related_name="fee_structures",
                        to="academic.classlevel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fee_structures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade_levels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave blank to apply to all grade levels",
                        related_name="fee_structures",
                        to="academic.gradelevel",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply to all terms in the academic year",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year", "term", "fee_type"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("paid_to", models.CharField(max_length=255)),
                (
                    "paid_through",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cheque", "Cheque"),
                            ("Mobile Money", "Mobile Money"),
                            ("Card", "Card"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, transfer reference, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="If payment is to a system user (teacher, accountant, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.paymentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-payment_number"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("payer", models.CharField(default="Unknown", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_through",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cheque", "Cheque"),
                            ("Mobile Money", "Mobile Money"),
                            ("Card", "Card"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (bank ref, mobile money ref, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="academic.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-receipt_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentFeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_owed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Can be different from fee_structure.amount for discounts/adjustments",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "is_waived",
                    models.BooleanField(
                        default=False,
                        help_text="Waived fees (scholarships, etc.) don't need to be paid",
                    ),
                ),
                ("waived_reason", models.TextField(blank=True, null=True)),
                ("waived_date", models.DateTimeField(blank=True, null=True)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="finance.feestructure",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_assignments",
                        to="academic.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_assignments",
                        to="administration.term",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waived_fees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-term", "fee_structure__fee_type", "student"],
            },
        ),
        migrations.CreateModel(
            name="FeePaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of this receipt allocated to this fee",
                        max_digits=10,
                    ),
                ),
                ("allocated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_allocations",
                        to="finance.receipt",
                    ),
                ),
                (
                    "fee_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_allocations",
                        to="finance.studentfeeassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-allocated_date"],
            },
        ),
        migrations.CreateModel(
            name="FeeAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                ("adjusted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fee_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="finance.studentfeeassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-adjusted_date"],
            },
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["academic_year", "term"], name="finance_fee_academi_b9b163_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["is_mandatory"], name="finance_fee_is_mand_890b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["date"], name="finance_pay_date_091c4c_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["category"], name="finance_pay_categor_d335d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["student", "term"], name="finance_rec_student_2a5470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["receipt_number"], name="finance_rec_receipt_e3529a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["date"], name="finance_rec_date_d27303_idx"),
        ),
        migrations.AddIndex(
            model_name="studentfeeassignment",
            index=models.Index(
                fields=["student", "term"], name="finance_stu_student_18cb36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfeeassignment",
            index=models.Index(
                fields=["is_waived"], name="finance_stu_is_waiv_35b0b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentfeeassignment",
            unique_together={("student", "fee_structure", "term")},
        ),
        migrations.AddIndex(
            model_name="feepaymentallocation",
            index=models.Index(
                fields=["receipt", "fee_assignment"],
                name="finance_fee_receipt_5ec9a2_idx",
            ),
        ),
    ]
