# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeeAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                ("adjusted_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-adjusted_date"],
            },
        ),
        migrations.CreateModel(
            name="FeePaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of this receipt allocated to this fee",
                        max_digits=10,
                    ),
                ),
                ("allocated_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-allocated_date"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("Tuition", "Tuition"),
                            ("Transport", "Transport"),
                            ("Meals", "Meals"),
                            ("Books", "Books"),
                            ("Uniform", "Uniform"),
                            ("Other", "Other"),
                        ],
                        default="Tuition",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard amount for this fee",
                        max_digits=10,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Mandatory fees are auto-assigned to all applicable students",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Due date for this fee", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-academic_year", "term", "fee_type"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("paid_to", models.CharField(max_length=255)),
                (
                    "paid_through",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cheque", "Cheque"),
                            ("Mobile Money", "Mobile Money"),
                            ("Card", "Card"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, transfer reference, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-payment_number"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbr", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Payment Categories",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("payer", models.CharField(default="Unknown", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_through",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cheque", "Cheque"),
                            ("Mobile Money", "Mobile Money"),
                            ("Card", "Card"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (bank ref, mobile money ref, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date", "-receipt_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentFeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_owed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Can be different from fee_structure.amount for discounts/adjustments",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "is_waived",
                    models.BooleanField(
                        default=False,
                        help_text="Waived fees (scholarships, etc.) don't need to be paid",
                    ),
                ),
                ("waived_reason", models.TextField(blank=True, null=True)),
                ("waived_date", models.DateTimeField(blank=True, null=True)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-term", "fee_structure__fee_type", "student"],
            },
        ),
    ]
