# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0003_initial"),
        ("administration", "0002_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feeadjustment",
            name="adjusted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feepaymentallocation",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="administration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="class_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave blank to apply to all class levels",
                related_name="fee_structures",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_fee_structures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="grade_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave blank to apply to all grade levels",
                related_name="fee_structures",
                to="academic.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to apply to all terms in the academic year",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="administration.term",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="If payment is to a system user (teacher, accountant, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.paymentcategory",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="administration.term",
            ),
        ),
        migrations.AddField(
            model_name="feepaymentallocation",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_allocations",
                to="finance.receipt",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assignments",
                to="finance.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_assignments",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_assignments",
                to="administration.term",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="waived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waived_fees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feepaymentallocation",
            name="fee_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="finance.studentfeeassignment",
            ),
        ),
        migrations.AddField(
            model_name="feeadjustment",
            name="fee_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="finance.studentfeeassignment",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["academic_year", "term"], name="finance_fee_academi_b9b163_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["is_mandatory"], name="finance_fee_is_mand_890b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["date"], name="finance_pay_date_091c4c_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["category"], name="finance_pay_categor_d335d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["student", "term"], name="finance_rec_student_2a5470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["receipt_number"], name="finance_rec_receipt_e3529a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["date"], name="finance_rec_date_d27303_idx"),
        ),
        migrations.AddIndex(
            model_name="studentfeeassignment",
            index=models.Index(
                fields=["student", "term"], name="finance_stu_student_18cb36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfeeassignment",
            index=models.Index(
                fields=["is_waived"], name="finance_stu_is_waiv_35b0b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentfeeassignment",
            unique_together={("student", "fee_structure", "term")},
        ),
        migrations.AddIndex(
            model_name="feepaymentallocation",
            index=models.Index(
                fields=["receipt", "fee_assignment"],
                name="finance_fee_receipt_5ec9a2_idx",
            ),
        ),
    ]
