# Generated by Django 5.2.11 on 2026-07-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "days_before_due",
                    models.IntegerField(
                        help_text="Positive for days before due date, negative for overdue days."
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "message_template",
                    models.TextField(
                        help_text="Variables available: {{student_name}}, {{fee_name}}, {{amount_owed}}, {{due_date}}"
                    ),
                ),
                (
                    "partial_payment_template",
                    models.TextField(
                        blank=True,
                        help_text="Variables available: {{student_name}}, {{fee_name}}, {{balance}}, {{amount_paid}}, {{due_date}}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_settings",
                        to="finance.feestructure",
                    ),
                ),
            ],
        ),
    ]
