# Generated by Django 5.1 on 2025-11-15 13:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_student_is_active'),
        ('administration', '0002_initial'),
        ('finance', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('adjusted_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-adjusted_date'],
            },
        ),
        migrations.CreateModel(
            name='FeePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of this receipt allocated to this fee', max_digits=10)),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-allocated_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fee_type', models.CharField(choices=[('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Meals', 'Meals'), ('Books', 'Books'), ('Uniform', 'Uniform'), ('Other', 'Other')], default='Tuition', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Standard amount for this fee', max_digits=10)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mandatory fees are auto-assigned to all applicable students')),
                ('due_date', models.DateField(blank=True, help_text='Due date for this fee', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year', 'term', 'grade_level', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, help_text='Can be different from fee_structure.amount for discounts/adjustments', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_waived', models.BooleanField(default=False, help_text="Waived fees (scholarships, etc.) don't need to be paid")),
                ('waived_reason', models.TextField(blank=True, null=True)),
                ('waived_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-term', 'fee_structure__fee_type', 'student'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='debtrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='debtrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='debtrecord',
            name='term',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='debt_record',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_for',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='paid_for',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-payment_number']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date', '-receipt_number']},
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Cheque number, transfer reference, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference_number',
            field=models.CharField(blank=True, help_text='External reference number (bank ref, mobile money ref, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='users.accountant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_through',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Mobile Money', 'Mobile Money'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='If payment is to a system user (teacher, accountant, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='paid_through',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Mobile Money', 'Mobile Money'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_receipts', to='users.accountant'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='academic.student'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='administration.term'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['student', 'term'], name='finance_rec_student_2a5470_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='finance_rec_receipt_e3529a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['date'], name='finance_rec_date_d27303_idx'),
        ),
        migrations.AddField(
            model_name='feeadjustment',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepaymentallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepaymentallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='administration.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_level',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all class levels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academic.classlevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grade_level',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all grade levels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academic.gradelevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all terms in the academic year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='administration.term'),
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.paymentcategory'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='finance_pay_date_091c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['category'], name='finance_pay_categor_d335d9_idx'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='academic.student'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='administration.term'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepaymentallocation',
            name='fee_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.studentfeeassignment'),
        ),
        migrations.AddField(
            model_name='feeadjustment',
            name='fee_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.studentfeeassignment'),
        ),
        migrations.DeleteModel(
            name='DebtRecord',
        ),
        migrations.DeleteModel(
            name='PaymentAllocation',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.DeleteModel(
            name='ReceiptAllocation',
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['academic_year', 'term'], name='finance_fee_academi_b9b163_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['grade_level', 'class_level'], name='finance_fee_grade_l_e03271_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_mandatory'], name='finance_fee_is_mand_890b77_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['student', 'term'], name='finance_stu_student_18cb36_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['is_waived'], name='finance_stu_is_waiv_35b0b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeeassignment',
            unique_together={('student', 'fee_structure', 'term')},
        ),
        migrations.AddIndex(
            model_name='feepaymentallocation',
            index=models.Index(fields=['receipt', 'fee_assignment'], name='finance_fee_receipt_5ec9a2_idx'),
        ),
    ]
