# Generated by Django 5.1 on 2025-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_student_is_active'),
        ('finance', '0003_feeadjustment_feepaymentallocation_feestructure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-academic_year', 'term', 'fee_type']},
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='finance_fee_grade_l_e03271_idx',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_levels',
            field=models.ManyToManyField(blank=True, help_text='Leave blank to apply to all class levels', related_name='fee_structures', to='academic.classlevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, help_text='Leave blank to apply to all grade levels', related_name='fee_structures', to='academic.gradelevel'),
        ),
    ]
