# Generated by Django 5.1 on 2025-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_no',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_no',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
