# Generated by Django 5.2.11 on 2026-08-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_allocatedsubject_is_mandatory"),
        ("finance", "0003_remindersetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("Tuition", "Tuition"),
                            ("Transport", "Transport"),
                            ("Meals", "Meals"),
                            ("Books", "Books"),
                            ("Uniform", "Uniform"),
                            ("Other", "Other"),
                        ],
                        help_text="The type of fee generated by this service",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="feestructure",
            name="optional_service",
            field=models.ForeignKey(
                blank=True,
                help_text="If linked to a service, this fee will be auto-assigned to subscribed students",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_structures",
                to="finance.optionalservice",
            ),
        ),
        migrations.CreateModel(
            name="ServiceSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscribed_on", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="finance.optionalservice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_subscriptions",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-subscribed_on"],
                "unique_together": {("student", "service")},
            },
        ),
    ]
