# Generated by Django 5.2.11 on 2026-08-19 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_allocatedsubject_is_mandatory"),
        ("finance", "0004_optionalservice_feestructure_optional_service_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Fee Assigned", "Fee Assigned"),
                            ("Bulk Fee Assigned", "Bulk Fee Assigned"),
                            ("Fee Waived", "Fee Waived"),
                            ("Amount Adjusted", "Amount Adjusted"),
                            ("Payment Recorded", "Payment Recorded"),
                            ("Payment Reversed", "Payment Reversed"),
                            ("Service Subscribed", "Service Subscribed"),
                            ("Service Unsubscribed", "Service Unsubscribed"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human readable description of the action taken."
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data payload for debugging (e.g. original vs new amount).",
                    ),
                ),
                (
                    "target_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to="academic.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
