# Generated by Django 5.1 on 2025-03-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_student_options_remove_teacher_isteacher'),
        ('administration', '0003_alter_term_default_term_fee'),
        ('finance', '0004_remove_payment_payment_no_remove_receipt_receipt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='paid_through',
            field=models.CharField(choices=[('CRDB', 'CRDB'), ('NMB', 'NMB'), ('NBC', 'NBC'), ('HATI MALIPO', 'HATI MALIPO'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payer',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_records', to='academic.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
