# Generated by Django 5.1 on 2025-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_receipt_paid_through_alter_receipt_payer_debtrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
