# Generated by Django 5.1 on 2025-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_receipt_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_through',
            field=models.CharField(choices=[('CRDB', 'CRDB'), ('NMB', 'NMB'), ('NBC', 'NBC'), ('HATI MALIPO', 'HATI MALIPO'), ('CASH', 'CASH'), ('Unknown', 'Unknown')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='paid_through',
            field=models.CharField(choices=[('CRDB', 'CRDB'), ('NMB', 'NMB'), ('NBC', 'NBC'), ('HATI MALIPO', 'HATI MALIPO'), ('CASH', 'CASH'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
