# Generated by Django 5.1 on 2025-06-18 19:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_student_debt'),
        ('finance', '0007_payment_paid_through_alter_receipt_paid_through'),
        ('users', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtrecord',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AddField(
            model_name='debtrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='debtrecord',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtrecord',
            name='reversed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debtrecord',
            name='amount_added',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('debt_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.debtrecord')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.accountant')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='finance.receipt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academic.student')),
            ],
        ),
    ]
