# Generated by Django on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_feestructure_remove_class_levels_add_classrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("Tuition", "Tuition"),
                    ("Admission", "Admission"),
                    ("Transport", "Transport"),
                    ("Meals", "Meals"),
                    ("Exam", "Exam"),
                    ("Library", "Library"),
                    ("Laboratory", "Laboratory"),
                    ("Sports", "Sports"),
                    ("Maintenance", "Maintenance"),
                    ("Books", "Books"),
                    ("Uniform", "Uniform"),
                    ("Other", "Other"),
                ],
                default="Tuition",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="optionalservice",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("Tuition", "Tuition"),
                    ("Admission", "Admission"),
                    ("Transport", "Transport"),
                    ("Meals", "Meals"),
                    ("Exam", "Exam"),
                    ("Library", "Library"),
                    ("Laboratory", "Laboratory"),
                    ("Sports", "Sports"),
                    ("Maintenance", "Maintenance"),
                    ("Books", "Books"),
                    ("Uniform", "Uniform"),
                    ("Other", "Other"),
                ],
                help_text="The type of fee generated by this service",
                max_length=50,
            ),
        ),
    ]
