# Generated by Django 5.1 on 2025-07-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_academicyear_graduation_date'),
        ('finance', '0008_alter_debtrecord_options_debtrecord_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term'),
        ),
    ]
