# Generated by Django 5.2.11 on 2026-09-05 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_initial"),
        ("finance", "0012_studentfeeassignment_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeTermSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional term-specific override amount. If null, falls back to FeeStructure.amount.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Authoritative due date for fee assignments generated in this term"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        help_text="Parent recurring fee structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_schedules",
                        to="finance.feestructure",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Specific academic term for this schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_term_schedules",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["term__start_date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fee_structure", "term"),
                        name="finance_unique_fee_structure_term_schedule",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__isnull", True), ("amount__gt", 0), _connector="OR"
                        ),
                        name="finance_schedule_amount_positive",
                    ),
                ],
            },
        ),
    ]
