# Generated by Django 5.2.11 on 2026-09-05 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0029_parent_alt_phone"),
        ("administration", "0002_initial"),
        ("finance", "0013_feetermschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentfeeassignment",
            options={
                "ordering": [
                    "-term",
                    "fee_structure__fee_type",
                    "student",
                    "charge_number",
                ]
            },
        ),
        migrations.RemoveConstraint(
            model_name="studentfeeassignment",
            name="finance_assignment_uniq_onetime_student_key",
        ),
        migrations.RemoveConstraint(
            model_name="studentfeeassignment",
            name="finance_assignment_uniq_annual_student_key_year",
        ),
        migrations.AlterUniqueTogether(
            name="studentfeeassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentfeeassignment",
            name="charge_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Sequence index for repeatable manual fee charges (defaults to 1 for standard fees)",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfeeassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("charge_number__gte", 1)),
                name="finance_assignment_charge_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfeeassignment",
            constraint=models.UniqueConstraint(
                fields=("student", "fee_structure", "term", "charge_number"),
                name="finance_assignment_uniq_student_fee_term_charge",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfeeassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("recurrence", "ONE_TIME"),
                    models.Q(("logical_fee_key", ""), _negated=True),
                ),
                fields=("student", "logical_fee_key", "charge_number"),
                name="finance_assignment_uniq_onetime_student_key_charge",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfeeassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("recurrence", "ANNUAL"),
                    models.Q(("logical_fee_key", ""), _negated=True),
                    ("academic_year__isnull", False),
                ),
                fields=("student", "logical_fee_key", "academic_year", "charge_number"),
                name="finance_assignment_uniq_annual_student_key_year_charge",
            ),
        ),
    ]
