# Generated by Django 5.2.11 on 2026-09-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_studentfeeassignment_charge_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepaymentallocation",
            name="fee_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="finance.studentfeeassignment",
            ),
        ),
        migrations.AlterField(
            model_name="studentfeeassignment",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_assignments",
                to="finance.feestructure",
            ),
        ),
    ]
