from .structure import (
    ClassYearSerializer,
    DepartmentSerializer,
    StreamSerializer,
    SchoolSectionSerializer,
    GradeLevelSerializer,
    ClassRoomSerializer,
    SchoolYearSerializer,
    ReasonLeftSerializer,
    BulkUploadClassRoomsSerializer,
    BulkUploadSubjectsSerializer,
)

from .staff import (
    SubjectSerializer,
    AllocatedSubjectSerializer,
    AllocatedSubjectListSerializer,
    MessageToTeacherSerializer,
    StaffSerializer,
)

from .curriculum import (
    CurriculumClassSerializer,
    CurriculumSerializer,
    CurriculumSubjectSerializer,
    TopicSerializer,
    CurriculumTopicSerializer,
    CurriculumGuidanceSerializer,
    SubTopicSerializer,
    LearningObjectiveSerializer,
    PublishedSchemeSerializer,
    PublishedSchemeEntrySerializer,
    CurriculumResourceSerializer,
)

from .scheme_and_lesson import (
    SchemeOfWorkSerializer,
    SchemeOfWorkItemSerializer,
    LessonPlanSerializer,
    LessonDeliverySerializer,
    LessonPlanMaterialSerializer,
    PublishedSchemeAdoptionSerializer,
)

from .leadership import (
    AcademicLeadershipAssignmentSerializer,
    AcademicApprovalPolicySerializer,
)

from .student import (
    ParentSerializer,
    StudentSerializer,
    StudentsMedicalHistorySerializer,
    StudentsPreviousAcademicHistorySerializer,
    StudentFileSerializer,
    StudentHealthRecordSerializer,
    MessageToParentSerializer,
    StudentClassEnrollmentSerializer,
    PromotionRuleSerializer,
    StudentPromotionSerializer,
    PromotionPreviewSerializer,
    StreamAssignmentSerializer,
    ClassMovementPreviewSerializer,
    ClassMovementExecutionSerializer,
    CapacityWarningSerializer,
    NewClassroomNeededSerializer,
    StudentRegistrationSerializer,
    StudentLoginSerializer,
    StudentProfileSerializer,
    StudentDashboardSerializer,
    BulkCreateStudentsProfileSerializer,
    BulkUploadStudentsSerializer,
)

from .admission import (
    AdmissionSessionSerializer,
    AdmissionSessionListSerializer,
    AdmissionSessionPublicSerializer,
    AdmissionFeeStructureSerializer,
    AdmissionFeeStructurePublicSerializer,
    AdmissionApplicationListSerializer,
    AdmissionApplicationDetailSerializer,
    PublicAdmissionApplicationSerializer,
    AdmissionApplicationCreateSerializer,
    AdmissionApplicationUpdateSerializer,
    AdmissionApplicationStatusUpdateSerializer,
    AdmissionDocumentSerializer,
    PublicAdmissionDocumentSerializer,
    PublicAdmissionDocumentUploadSerializer,
    AdmissionDocumentVerifySerializer,
    AssessmentCriterionSerializer,
    AdmissionAssessmentListSerializer,
    AdmissionAssessmentDetailSerializer,
    AdmissionAssessmentCreateSerializer,
    AdmissionAssessmentScoreSerializer,
    AssessmentTemplateCriterionSerializer,
    AssessmentTemplateListSerializer,
    AssessmentTemplateDetailSerializer,
    AdmissionStatisticsSerializer,
    ApplicationTrackingSerializer,
    StudentAdmissionNumberPolicySerializer,
    AdmissionApplicationNumberPolicySerializer,
)

__all__ = [
    # Structure
    "ClassYearSerializer",
    "DepartmentSerializer",
    "StreamSerializer",
    "SchoolSectionSerializer",
    "GradeLevelSerializer",
    "ClassRoomSerializer",
    "SchoolYearSerializer",
    "ReasonLeftSerializer",
    "BulkUploadClassRoomsSerializer",
    "BulkUploadSubjectsSerializer",
    # Staff
    "SubjectSerializer",
    "AllocatedSubjectSerializer",
    "AllocatedSubjectListSerializer",
    "MessageToTeacherSerializer",
    "StaffSerializer",
    # Curriculum
    "CurriculumClassSerializer",
    "CurriculumSerializer",
    "CurriculumSubjectSerializer",
    "TopicSerializer",
    "CurriculumTopicSerializer",
    "CurriculumGuidanceSerializer",
    "SubTopicSerializer",
    "LearningObjectiveSerializer",
    "PublishedSchemeSerializer",
    "PublishedSchemeEntrySerializer",
    "CurriculumResourceSerializer",
    # Scheme & Lesson
    "SchemeOfWorkSerializer",
    "SchemeOfWorkItemSerializer",
    "LessonPlanSerializer",
    "LessonDeliverySerializer",
    "LessonPlanMaterialSerializer",
    "PublishedSchemeAdoptionSerializer",
    # Leadership
    "AcademicLeadershipAssignmentSerializer",
    "AcademicApprovalPolicySerializer",
    # Student
    "ParentSerializer",
    "StudentSerializer",
    "StudentsMedicalHistorySerializer",
    "StudentsPreviousAcademicHistorySerializer",
    "StudentFileSerializer",
    "StudentHealthRecordSerializer",
    "MessageToParentSerializer",
    "StudentClassEnrollmentSerializer",
    "PromotionRuleSerializer",
    "StudentPromotionSerializer",
    "PromotionPreviewSerializer",
    "StreamAssignmentSerializer",
    "ClassMovementPreviewSerializer",
    "ClassMovementExecutionSerializer",
    "CapacityWarningSerializer",
    "NewClassroomNeededSerializer",
    "StudentRegistrationSerializer",
    "StudentLoginSerializer",
    "StudentProfileSerializer",
    "StudentDashboardSerializer",
    "BulkCreateStudentsProfileSerializer",
    "BulkUploadStudentsSerializer",
    # Admission
    "AdmissionSessionSerializer",
    "AdmissionSessionListSerializer",
    "AdmissionSessionPublicSerializer",
    "AdmissionFeeStructureSerializer",
    "AdmissionFeeStructurePublicSerializer",
    "AdmissionApplicationListSerializer",
    "AdmissionApplicationDetailSerializer",
    "PublicAdmissionApplicationSerializer",
    "AdmissionApplicationCreateSerializer",
    "AdmissionApplicationUpdateSerializer",
    "AdmissionApplicationStatusUpdateSerializer",
    "AdmissionDocumentSerializer",
    "PublicAdmissionDocumentSerializer",
    "PublicAdmissionDocumentUploadSerializer",
    "AdmissionDocumentVerifySerializer",
    "AssessmentCriterionSerializer",
    "AdmissionAssessmentListSerializer",
    "AdmissionAssessmentDetailSerializer",
    "AdmissionAssessmentCreateSerializer",
    "AdmissionAssessmentScoreSerializer",
    "AssessmentTemplateCriterionSerializer",
    "AssessmentTemplateListSerializer",
    "AssessmentTemplateDetailSerializer",
    "AdmissionStatisticsSerializer",
    "ApplicationTrackingSerializer",
    "StudentAdmissionNumberPolicySerializer",
    "AdmissionApplicationNumberPolicySerializer",
]
