# Generated by Django 5.2.11 on 2026-07-21 13:00

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("cached_student_count", models.PositiveIntegerField(default=0)),
                ("cached_teacher_count", models.PositiveIntegerField(default=0)),
                ("stats_last_synced", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current lifecycle state of the tenant",
                        max_length=20,
                    ),
                ),
                (
                    "has_mobile_access",
                    models.BooleanField(
                        default=False,
                        help_text="Enable mobile app access (iOS/Android apps)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="School logo (appears in emails and portal)",
                        null=True,
                        upload_to="tenant_logos/",
                    ),
                ),
                (
                    "motto",
                    models.CharField(
                        blank=True,
                        help_text="School motto (appears in emails and portal)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#047857",
                        help_text="Primary brand color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="School website URL", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="School physical address", null=True
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("mobile_access_granted", models.DateField(blank=True, null=True)),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="True once the school admin has completed (or skipped) the first-run setup wizard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inspector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Senior Education Officer"',
                        max_length=100,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Federal Ministry of Education"',
                        max_length=150,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("global", "All Schools"),
                            ("assigned", "Assigned Schools"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["user__email"],
            },
        ),
    ]
