# Generated by Django 5.2.11 on 2026-02-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(
                blank=True, help_text="School physical address", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="School logo (appears in emails and portal)",
                null=True,
                upload_to="tenant_logos/",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="primary_color",
            field=models.CharField(
                default="#047857",
                help_text="Primary brand color (hex code)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.URLField(
                blank=True, help_text="School website URL", null=True
            ),
        ),
    ]
