# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.client",
            ),
        ),
        migrations.AddField(
            model_name="inspector",
            name="assigned_tenants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Visible schools — only applies when access_level = assigned",
                related_name="inspectors",
                to="tenants.client",
            ),
        ),
        migrations.AddField(
            model_name="inspector",
            name="user",
            field=models.OneToOneField(
                help_text="Login account for this inspector",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspector_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
