# Generated by Django 5.1 on 2025-12-15 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='The primary admin user created during onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the initial setup wizard has been completed'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
