# Generated by Django 5.2.11 on 2026-02-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_client_address_client_logo_client_primary_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
