# Generated by Django 5.1 on 2025-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_admin_user_tenant_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current onboarding step (1–4)'),
        ),
    ]
