# Generated by Django 5.2.11 on 2026-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="pending_admin_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="pending_admin_first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="pending_admin_last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="pending_admin_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
