# Generated by Django 5.1 on 2025-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'School Information'), (2, 'Admin Account'), (3, 'Branding'), (4, 'Completed')], default=1, help_text='Current onboarding step'),
        ),
    ]
