# Generated by Django 5.2.11 on 2026-02-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_client_contact_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolSettings",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_active",
        ),
        migrations.AddField(
            model_name="client",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="cached_student_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="cached_teacher_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="stats_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                help_text="Current lifecycle state of the tenant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="suspension_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
