# Generated by Django 5.2.11 on 2026-07-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_client_pending_admin_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("provisioning", "Provisioning"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("rejected", "Rejected"),
                    ("failed", "Provisioning Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Current lifecycle state of the tenant",
                max_length=20,
            ),
        ),
    ]
