# Generated by Django 5.2.11 on 2026-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_alter_client_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="cached_parent_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
