# Generated by Django 5.1 on 2025-12-17 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_onboarding_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#1E40AF', max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('onboarding_step', models.PositiveSmallIntegerField(choices=[(1, 'School Information'), (2, 'Admin Account'), (3, 'Branding'), (4, 'Completed')], default=1, help_text='Current onboarding step')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether the initial setup wizard has been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='The primary admin user created during onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
