# Generated by Django 5.1 on 2025-12-17 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_schoolsettings_delete_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year_start_month',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=9, help_text='Month when academic year starts (1=January, 12=December)', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='terms_per_year',
            field=models.IntegerField(blank=True, choices=[(2, '2 Terms'), (3, '3 Terms'), (4, '4 Terms (Quarters)')], default=3, help_text='Number of terms per academic year', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
