# Generated by Django 5.2.11 on 2026-03-04 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_inspector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspector",
            name="assigned_tenants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Visible schools — only applies when access_level = assigned",
                related_name="inspectors",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal admin notes"),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="organisation",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Federal Ministry of Education"',
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="title",
            field=models.CharField(
                blank=True, help_text='e.g. "Senior Education Officer"', max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="user",
            field=models.OneToOneField(
                help_text="Login account for this inspector",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspector_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
