# Generated by Django 5.1 on 2025-12-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_schoolsettings_contact_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='phone',
            new_name='contact_phone',
        ),
    ]
