# Generated by Django 5.1 on 2026-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_rename_phone_schoolsettings_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#047857', max_length=20),
        ),
    ]
