# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import examination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualSubjectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_term",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "second_term",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "third_term",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "annual_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("grade", models.CharField(max_length=20)),
                (
                    "grade_point",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("is_pass", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNMENT", "Assignment"),
                            ("TEST", "Test"),
                            ("PROJECT", "Project"),
                            ("PRACTICAL", "Practical"),
                            ("EXAMINATION", "Examination"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("ends_date", models.DateField()),
                ("out_of", models.IntegerField()),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="Comments Regarding Exam",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GradeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=20)),
                ("remark", models.CharField(max_length=100)),
                (
                    "grade_point",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-min_score"],
            },
        ),
        migrations.CreateModel(
            name="GradingScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRE_PRIMARY", "Pre-Primary Education"),
                            ("PRIMARY", "Primary Education"),
                            ("JSS", "Junior Secondary School"),
                            ("SSS", "Senior Secondary School"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarkedScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "script_file",
                    models.FileField(
                        help_text="Marked exam script file (PDF, images, etc.) - Max 1MB",
                        upload_to="examination/marked_scripts/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                            ),
                            examination.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original filename", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Upload timestamp"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the marked script",
                        null=True,
                    ),
                ),
                (
                    "visible_to_student",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student can view this marked script",
                    ),
                ),
                (
                    "visible_to_parent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether parent can view this marked script",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marked Script",
                "verbose_name_plural": "Marked Scripts",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_computation_method",
                    models.CharField(
                        choices=[
                            ("AVERAGE_ALL_TERMS", "Average of all three terms"),
                            (
                                "FINAL_TERM_ONLY",
                                "Third term result is the annual result",
                            ),
                        ],
                        default="AVERAGE_ALL_TERMS",
                        max_length=30,
                    ),
                ),
                (
                    "minimum_average",
                    models.DecimalField(decimal_places=2, default=40, max_digits=5),
                ),
                (
                    "minimum_subject_pass",
                    models.DecimalField(decimal_places=2, default=40, max_digits=5),
                ),
                ("max_failed_subjects", models.PositiveIntegerField(default=99)),
                ("auto_promote", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file",
                        null=True,
                        upload_to="report_cards/%Y/%m/",
                    ),
                ),
                (
                    "generated_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the PDF was generated"
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "last_downloaded",
                    models.DateTimeField(
                        blank=True, help_text="Last download timestamp", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Card",
                "verbose_name_plural": "Report Cards",
                "ordering": ["-generated_date"],
            },
        ),
        migrations.CreateModel(
            name="ResultAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("COMPUTED", "Computed"),
                            ("RECOMPUTED", "Recomputed"),
                            ("HOMEROOM_APPROVED", "Homeroom Approved"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("UNPUBLISHED", "Unpublished"),
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SubjectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grading_scheme_name", models.CharField(blank=True, max_length=100)),
                ("grading_rule_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, help_text="CA + Exam score", max_digits=5
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="Percentage score", max_digits=5
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=100)),
                (
                    "grade",
                    models.CharField(
                        help_text="Letter grade for this subject", max_length=20
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade point (0.00 - 4.00)",
                        max_digits=3,
                    ),
                ),
                ("teacher_comment", models.TextField(blank=True)),
                (
                    "position_in_subject",
                    models.IntegerField(
                        blank=True,
                        help_text="Student's rank in this subject within the class",
                        null=True,
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Total students who took this subject",
                        null=True,
                    ),
                ),
                (
                    "highest_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Highest score in class for this subject",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "lowest_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lowest score in class for this subject",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "class_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class average for this subject",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_pass", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subject Result",
                "verbose_name_plural": "Subject Results",
                "ordering": ["subject__subject_code", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="TermResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_name", models.CharField(max_length=100)),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of all subject scores",
                        max_digits=10,
                    ),
                ),
                (
                    "average_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average percentage across all subjects",
                        max_digits=5,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        help_text="Overall grade for the term", max_length=20
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade Point Average (0.00 - 4.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "position_in_class",
                    models.IntegerField(
                        blank=True, help_text="Student's rank in the class", null=True
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of students in class",
                        null=True,
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=100)),
                (
                    "class_teacher_remarks",
                    models.TextField(
                        blank=True, help_text="Remarks from class teacher", null=True
                    ),
                ),
                (
                    "principal_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Remarks from principal/head teacher",
                        null=True,
                    ),
                ),
                (
                    "computed_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the result was computed",
                    ),
                ),
                ("homeroom_approved", models.BooleanField(default=False)),
                ("homeroom_approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether result is visible to parents/students",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="When the result was published", null=True
                    ),
                ),
                ("is_pass", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_reason", models.TextField(blank=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("result_release_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Term Result",
                "verbose_name_plural": "Term Results",
                "ordering": [
                    "-academic_year__start_date",
                    "-term__start_date",
                    "position_in_class",
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnualResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                ("gpa", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                (
                    "position_in_class",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_students", models.PositiveIntegerField(blank=True, null=True)),
                ("is_promoted", models.BooleanField(default=True)),
                ("promotion_reason", models.TextField(blank=True)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_results",
                        to="administration.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academic.classroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__start_date", "position_in_class"],
            },
        ),
    ]
