# Generated by Django 5.2.11 on 2026-02-20 10:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("administration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExaminationListHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("ends_date", models.DateField()),
                ("out_of", models.IntegerField()),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="Comments Regarding Exam",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "classrooms",
                    models.ManyToManyField(
                        related_name="class_exams", to="academic.classroom"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarksManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_scored", models.FloatField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks_entered",
                        to="academic.teacher",
                    ),
                ),
                (
                    "exam_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_marks",
                        to="examination.examinationlisthandler",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_marks",
                        to="academic.studentclassenrollment",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_marks",
                        to="academic.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gpa", models.FloatField(null=True)),
                ("cat_gpa", models.FloatField(null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                    ),
                ),
                (
                    "term",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of all subject scores",
                        max_digits=10,
                    ),
                ),
                (
                    "total_possible",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total possible marks across all subjects",
                        max_digits=10,
                    ),
                ),
                (
                    "average_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average percentage across all subjects",
                        max_digits=5,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Excellent (A)"),
                            ("B", "Very Good (B)"),
                            ("C", "Good (C)"),
                            ("D", "Pass (D)"),
                            ("E", "Poor (E)"),
                            ("F", "Fail (F)"),
                        ],
                        help_text="Overall grade for the term",
                        max_length=2,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade Point Average (0.00 - 4.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "position_in_class",
                    models.IntegerField(
                        blank=True, help_text="Student's rank in the class", null=True
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of students in class",
                        null=True,
                    ),
                ),
                (
                    "class_teacher_remarks",
                    models.TextField(
                        blank=True, help_text="Remarks from class teacher", null=True
                    ),
                ),
                (
                    "principal_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Remarks from principal/head teacher",
                        null=True,
                    ),
                ),
                (
                    "computed_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the result was computed",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether result is visible to parents/students",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="When the result was published", null=True
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_results",
                        to="administration.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Classroom at the time of result computation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academic.classroom",
                    ),
                ),
                (
                    "computed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="computed_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_results",
                        to="academic.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_results",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Result",
                "verbose_name_plural": "Term Results",
                "ordering": [
                    "-academic_year__start_date",
                    "-term__start_date",
                    "position_in_class",
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ca_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Continuous Assessment score (usually 40%)",
                        max_digits=5,
                    ),
                ),
                (
                    "ca_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        help_text="Maximum CA score possible",
                        max_digits=5,
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Examination score (usually 60%)",
                        max_digits=5,
                    ),
                ),
                (
                    "exam_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        help_text="Maximum exam score possible",
                        max_digits=5,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, help_text="CA + Exam score", max_digits=5
                    ),
                ),
                (
                    "total_possible",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Maximum possible score (usually 100)",
                        max_digits=5,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="Percentage score", max_digits=5
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Excellent (A)"),
                            ("B", "Very Good (B)"),
                            ("C", "Good (C)"),
                            ("D", "Pass (D)"),
                            ("E", "Poor (E)"),
                            ("F", "Fail (F)"),
                        ],
                        help_text="Letter grade for this subject",
                        max_length=2,
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade point (0.00 - 4.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "position_in_subject",
                    models.IntegerField(
                        blank=True,
                        help_text="Student's rank in this subject within the class",
                        null=True,
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Total students who took this subject",
                        null=True,
                    ),
                ),
                (
                    "highest_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Highest score in class for this subject",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "lowest_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lowest score in class for this subject",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "class_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class average for this subject",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "teacher_remarks",
                    models.TextField(
                        blank=True, help_text="Subject teacher's remarks", null=True
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_results",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who taught this subject",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academic.teacher",
                    ),
                ),
                (
                    "term_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_results",
                        to="examination.termresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Result",
                "verbose_name_plural": "Subject Results",
                "ordering": ["subject__subject_code", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file",
                        null=True,
                        upload_to="report_cards/%Y/%m/",
                    ),
                ),
                (
                    "generated_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the PDF was generated"
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "last_downloaded",
                    models.DateTimeField(
                        blank=True, help_text="Last download timestamp", null=True
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_report_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term_result",
                    models.OneToOneField(
                        help_text="Associated term result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_card",
                        to="examination.termresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Card",
                "verbose_name_plural": "Report Cards",
                "ordering": ["-generated_date"],
            },
        ),
        migrations.CreateModel(
            name="GradeScaleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_grade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_grade", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "letter_grade",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "numeric_scale",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "grade_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.gradescale",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["min_grade", "max_grade", "grade_scale"],
                        name="examination_min_gra_eab956_idx",
                    )
                ],
                "unique_together": {("min_grade", "max_grade", "grade_scale")},
            },
        ),
        migrations.CreateModel(
            name="MarkedScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "script_file",
                    models.FileField(
                        help_text="Marked exam script file (PDF, images, etc.)",
                        upload_to="examination/marked_scripts/%Y/%m/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original filename", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Upload timestamp"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the marked script",
                        null=True,
                    ),
                ),
                (
                    "visible_to_student",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student can view this marked script",
                    ),
                ),
                (
                    "visible_to_parent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether parent can view this marked script",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        help_text="Associated examination/assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marked_scripts",
                        to="examination.examinationlisthandler",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student whose script this is",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marked_scripts",
                        to="academic.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject of the assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marked_scripts",
                        to="academic.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Teacher who uploaded the script",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_marked_scripts",
                        to="academic.teacher",
                    ),
                ),
                (
                    "marks_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated marks entry (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_scripts",
                        to="examination.marksmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marked Script",
                "verbose_name_plural": "Marked Scripts",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["exam", "student", "subject"],
                        name="examination_exam_id_f2b785_idx",
                    ),
                    models.Index(
                        fields=["student"], name="examination_student_a50ac6_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="examination_uploade_d5df16_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="examination_uploade_e4ac15_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="termresult",
            index=models.Index(
                fields=["student", "term"], name="examination_student_84db5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termresult",
            index=models.Index(
                fields=["classroom", "term"], name="examination_classro_62652b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termresult",
            index=models.Index(
                fields=["is_published"], name="examination_is_publ_76fa38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termresult",
            unique_together={("student", "term", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="subjectresult",
            index=models.Index(
                fields=["term_result", "subject"], name="examination_term_re_0fc434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectresult",
            index=models.Index(
                fields=["subject", "grade"], name="examination_subject_a67d0b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectresult",
            unique_together={("term_result", "subject")},
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["term_result"], name="examination_term_re_0de16f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["generated_date"], name="examination_generat_f98f86_idx"
            ),
        ),
    ]
