# Generated by Django 5.1 on 2025-12-04 08:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_teacher_nssf_number'),
        ('administration', '0002_initial'),
        ('examination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Sum of all subject scores', max_digits=10)),
                ('total_possible', models.DecimalField(decimal_places=2, help_text='Total possible marks across all subjects', max_digits=10)),
                ('average_percentage', models.DecimalField(decimal_places=2, help_text='Average percentage across all subjects', max_digits=5)),
                ('grade', models.CharField(choices=[('A', 'Excellent (A)'), ('B', 'Very Good (B)'), ('C', 'Good (C)'), ('D', 'Pass (D)'), ('E', 'Poor (E)'), ('F', 'Fail (F)')], help_text='Overall grade for the term', max_length=2)),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Grade Point Average (0.00 - 4.00)', max_digits=3)),
                ('position_in_class', models.IntegerField(blank=True, help_text="Student's rank in the class", null=True)),
                ('total_students', models.IntegerField(blank=True, help_text='Total number of students in class', null=True)),
                ('class_teacher_remarks', models.TextField(blank=True, help_text='Remarks from class teacher', null=True)),
                ('principal_remarks', models.TextField(blank=True, help_text='Remarks from principal/head teacher', null=True)),
                ('computed_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the result was computed')),
                ('is_published', models.BooleanField(default=False, help_text='Whether result is visible to parents/students')),
                ('published_date', models.DateTimeField(blank=True, help_text='When the result was published', null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='administration.academicyear')),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom at the time of result computation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classroom')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='academic.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='administration.term')),
            ],
            options={
                'verbose_name': 'Term Result',
                'verbose_name_plural': 'Term Results',
                'ordering': ['-academic_year__start_date', '-term__start_date', 'position_in_class'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Continuous Assessment score (usually 40%)', max_digits=5)),
                ('ca_max', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Maximum CA score possible', max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Examination score (usually 60%)', max_digits=5)),
                ('exam_max', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Maximum exam score possible', max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, help_text='CA + Exam score', max_digits=5)),
                ('total_possible', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum possible score (usually 100)', max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage score', max_digits=5)),
                ('grade', models.CharField(choices=[('A', 'Excellent (A)'), ('B', 'Very Good (B)'), ('C', 'Good (C)'), ('D', 'Pass (D)'), ('E', 'Poor (E)'), ('F', 'Fail (F)')], help_text='Letter grade for this subject', max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='Grade point (0.00 - 4.00)', max_digits=3)),
                ('position_in_subject', models.IntegerField(blank=True, help_text="Student's rank in this subject within the class", null=True)),
                ('total_students', models.IntegerField(blank=True, help_text='Total students who took this subject', null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, help_text='Highest score in class for this subject', max_digits=5, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest score in class for this subject', max_digits=5, null=True)),
                ('class_average', models.DecimalField(blank=True, decimal_places=2, help_text='Class average for this subject', max_digits=5, null=True)),
                ('teacher_remarks', models.TextField(blank=True, help_text="Subject teacher's remarks", null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='academic.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher who taught this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.teacher')),
                ('term_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='examination.termresult')),
            ],
            options={
                'verbose_name': 'Subject Result',
                'verbose_name_plural': 'Subject Results',
                'ordering': ['subject__subject_code', 'subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['student', 'term'], name='examination_student_84db5e_idx'),
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['classroom', 'term'], name='examination_classro_62652b_idx'),
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['is_published'], name='examination_is_publ_76fa38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termresult',
            unique_together={('student', 'term', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='subjectresult',
            index=models.Index(fields=['term_result', 'subject'], name='examination_term_re_0fc434_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectresult',
            index=models.Index(fields=['subject', 'grade'], name='examination_subject_a67d0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together={('term_result', 'subject')},
        ),
    ]
