# Generated by Django 5.2.11 on 2026-07-08 13:31

import django.core.validators
import examination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_alter_student_admission_date"),
        ("examination", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markedscript",
            name="script_file",
            field=models.FileField(
                help_text="Marked exam script file (PDF, images, etc.) - Max 5MB",
                upload_to="examination/marked_scripts/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    examination.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="markedscript",
            unique_together={("exam", "student", "subject")},
        ),
    ]
