# Generated by Django 5.1 on 2025-12-04 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_termresult_subjectresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file', null=True, upload_to='report_cards/%Y/%m/')),
                ('generated_date', models.DateTimeField(auto_now_add=True, help_text='When the PDF was generated')),
                ('download_count', models.IntegerField(default=0, help_text='Number of times downloaded')),
                ('last_downloaded', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL)),
                ('term_result', models.OneToOneField(help_text='Associated term result', on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='examination.termresult')),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-generated_date'],
                'indexes': [models.Index(fields=['term_result'], name='examination_term_re_0de16f_idx'), models.Index(fields=['generated_date'], name='examination_generat_f98f86_idx')],
            },
        ),
    ]
