# Generated by Django 5.2.11 on 2026-07-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_allocatedsubject_term'),
        ('examination', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedscript',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who uploaded the script', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_marked_scripts', to='academic.teacher'),
        ),
    ]
