# Generated by Django 5.2.11 on 2026-07-08 13:33

import django.core.validators
import examination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0002_alter_markedscript_script_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markedscript",
            name="script_file",
            field=models.FileField(
                help_text="Marked exam script file (PDF, images, etc.) - Max 1MB",
                upload_to="examination/marked_scripts/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    examination.models.validate_file_size,
                ],
            ),
        ),
    ]
