# Generated by Django 5.1 on 2025-12-26 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_admissionapplication_admissionassessment_and_more'),
        ('examination', '0003_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_file', models.FileField(help_text='Marked exam script file (PDF, images, etc.)', upload_to='examination/marked_scripts/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the marked script', null=True)),
                ('visible_to_student', models.BooleanField(default=False, help_text='Whether student can view this marked script')),
                ('visible_to_parent', models.BooleanField(default=False, help_text='Whether parent can view this marked script')),
                ('exam', models.ForeignKey(help_text='Associated examination/assessment', on_delete=django.db.models.deletion.CASCADE, related_name='marked_scripts', to='examination.examinationlisthandler')),
                ('marks_entry', models.ForeignKey(blank=True, help_text='Associated marks entry (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_scripts', to='examination.marksmanagement')),
                ('student', models.ForeignKey(help_text='Student whose script this is', on_delete=django.db.models.deletion.CASCADE, related_name='marked_scripts', to='academic.student')),
                ('subject', models.ForeignKey(help_text='Subject of the assessment', on_delete=django.db.models.deletion.CASCADE, related_name='marked_scripts', to='academic.subject')),
                ('uploaded_by', models.ForeignKey(help_text='Teacher who uploaded the script', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_marked_scripts', to='academic.teacher')),
            ],
            options={
                'verbose_name': 'Marked Script',
                'verbose_name_plural': 'Marked Scripts',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['exam', 'student', 'subject'], name='examination_exam_id_f2b785_idx'), models.Index(fields=['student'], name='examination_student_a50ac6_idx'), models.Index(fields=['uploaded_by'], name='examination_uploade_d5df16_idx'), models.Index(fields=['uploaded_at'], name='examination_uploade_e4ac15_idx')],
            },
        ),
    ]
