# Generated by Django 5.2.11 on 2026-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_alter_markedscript_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if generation failed', null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', help_text='Generation status', max_length=20),
        ),
    ]
