# Generated by Django 5.2.11 on 2026-07-30 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0004_reportcard_error_message_reportcard_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="termresult",
            old_name="is_approved",
            new_name="admin_approved",
        ),
        migrations.RenameField(
            model_name="termresult",
            old_name="approved_at",
            new_name="admin_approved_at",
        ),
        migrations.RenameField(
            model_name="termresult",
            old_name="approved_by",
            new_name="admin_approved_by",
        ),
        migrations.AddField(
            model_name="termresult",
            name="homeroom_approval_delegated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="termresult",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resultauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("COMPUTED", "Computed"),
                    ("RECOMPUTED", "Recomputed"),
                    ("HOMEROOM_APPROVED", "Homeroom Approved"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("LOCKED", "Locked"),
                    ("UNLOCKED", "Unlocked"),
                    ("PUBLISHED", "Published"),
                    ("UNPUBLISHED", "Unpublished"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resultauditlog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
