# Generated by Django 5.2.11 on 2026-07-31 08:40

import django.core.files.storage
import django.core.validators
import examination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0005_rename_is_approved_termresult_admin_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markedscript",
            name="script_file",
            field=models.FileField(
                help_text="Marked exam script file (PDF, images, etc.) - Max 10MB",
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="examination/marked_scripts/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    examination.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF file",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="report_cards/%Y/%m/",
            ),
        ),
    ]
