# Generated by Django 5.2.11 on 2026-08-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_allocatedsubject_is_mandatory"),
        ("examination", "0008_alter_markedscript_script_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="markedscript",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot classroom for this marked script",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_scripts",
                to="academic.classroom",
            ),
        ),
    ]
