# Generated by Django 5.2.11 on 2026-08-19 17:28

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import examination.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_schoolsection"),
        ("administration", "0002_initial"),
        ("examination", "0009_markedscript_classroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annualresult",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("COMPUTED", "Computed"),
                    ("HOMEROOM_APPROVED", "Homeroom Approved"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("LOCKED", "Locked"),
                    ("PUBLISHED", "Published"),
                ],
                default="COMPUTED",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="annualsubjectresult",
            name="first_term_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("NOT_OFFERED", "Not Offered"),
                    ("MISSING", "Missing"),
                    ("EXEMPTED", "Exempted"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="annualsubjectresult",
            name="position_in_subject",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annualsubjectresult",
            name="second_term_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("NOT_OFFERED", "Not Offered"),
                    ("MISSING", "Missing"),
                    ("EXEMPTED", "Exempted"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="annualsubjectresult",
            name="third_term_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("NOT_OFFERED", "Not Offered"),
                    ("MISSING", "Missing"),
                    ("EXEMPTED", "Exempted"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="missing_term_policy",
            field=models.CharField(
                choices=[
                    ("TREAT_AS_ZERO", "Treat missing terms as 0%"),
                    ("IGNORE_AND_AVERAGE", "Ignore missing terms and average the rest"),
                    (
                        "FAIL_SUBJECT",
                        "Automatically fail the subject if a term is missing",
                    ),
                ],
                default="IGNORE_AND_AVERAGE",
                help_text="How to handle missing terms when computing annual results",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="termresult",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("COMPUTED", "Computed"),
                    ("HOMEROOM_APPROVED", "Homeroom Approved"),
                    ("ADMIN_APPROVED", "Admin Approved"),
                    ("LOCKED", "Locked"),
                    ("PUBLISHED", "Published"),
                ],
                default="COMPUTED",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="annualresult",
            name="is_promoted",
            field=models.BooleanField(
                default=True, help_text="Legacy field. Use promotion_decision instead."
            ),
        ),
        migrations.AlterField(
            model_name="annualresult",
            name="promoted_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_promoted_students",
                to="academic.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="annual_computation_method",
            field=models.CharField(
                choices=[
                    ("AVERAGE_ALL_TERMS", "Average of all terms"),
                    ("FINAL_TERM_ONLY", "Third term result is the annual result"),
                    ("WEIGHTED_TERMS", "Use custom term weights"),
                ],
                default="AVERAGE_ALL_TERMS",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AcademicTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("history_snapshot", models.JSONField(default=dict)),
                (
                    "pdf_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="transcripts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            examination.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_transcript",
                        to="academic.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CumulativePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "computation_method",
                    models.CharField(
                        choices=[
                            ("AVERAGE_ANNUAL_RESULTS", "Average Annual Results"),
                            ("WEIGHTED_ANNUAL_RESULTS", "Weighted Annual Results"),
                            ("FINAL_YEAR_ONLY", "Final Year Only"),
                        ],
                        default="AVERAGE_ANNUAL_RESULTS",
                        max_length=50,
                    ),
                ),
                ("include_failed_years", models.BooleanField(default=True)),
                ("include_repeated_years", models.BooleanField(default=False)),
                (
                    "scheme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cumulative_policy",
                        to="examination.gradingscheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CumulativeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPUTED", "Computed"),
                            ("HOMEROOM_APPROVED", "Homeroom Approved"),
                            ("ADMIN_APPROVED", "Admin Approved"),
                            ("LOCKED", "Locked"),
                            ("PUBLISHED", "Published"),
                        ],
                        default="COMPUTED",
                        max_length=25,
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cumulative_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cumulative_gpa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="The latest academic year included in this cumulative result",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.academicyear",
                    ),
                ),
                (
                    "computed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grading_scheme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="examination.gradingscheme",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cumulative_results",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="PromotionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Promoted"),
                            ("NOT_PROMOTED", "Not Promoted"),
                            ("CONDITIONAL_PROMOTION", "Conditional Promotion"),
                            ("REPEAT_CLASS", "Repeat Class"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("GRADUATED", "Graduated"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=30,
                    ),
                ),
                (
                    "reasons",
                    models.TextField(
                        blank=True, help_text="Automated reasons for this decision"
                    ),
                ),
                ("failed_subjects_count", models.PositiveIntegerField(default=0)),
                ("is_overridden", models.BooleanField(default=False)),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annual_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_decision",
                        to="examination.annualresult",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promoted_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_decisions",
                        to="academic.gradelevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultAmendmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annual_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_requests",
                        to="examination.annualresult",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_requests",
                        to="examination.termresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CumulativeSubjectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cumulative_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                (
                    "grade_point",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "cumulative_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="examination.cumulativeresult",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("cumulative_result", "subject")},
            },
        ),
        migrations.CreateModel(
            name="TermWeightConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_number",
                    models.PositiveIntegerField(help_text="e.g. 1 for First Term"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage weight of this term (e.g. 30.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "promotion_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_weights",
                        to="examination.promotionrule",
                    ),
                ),
            ],
            options={
                "ordering": ["term_number"],
                "unique_together": {("promotion_rule", "term_number")},
            },
        ),
    ]
