# Generated by Django 5.2.11 on 2026-08-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_initial"),
        ("examination", "0010_annualresult_lifecycle_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmententry",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_entries",
                to="administration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="assessmententry",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="examination.assessmentsession",
            ),
        ),
        migrations.AddField(
            model_name="assessmententry",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CBT", "CBT"),
                    ("IMPORT", "Import"),
                    ("API", "API"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessmententry",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETE", "Complete"),
                    ("INCOMPLETE", "Incomplete"),
                    ("PENDING", "Pending"),
                    ("MISSING", "Missing"),
                    ("ABSENT", "Absent"),
                    ("EXEMPTED", "Exempted"),
                    ("NOT_OFFERED", "Not Offered"),
                ],
                default="COMPLETE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessmententry",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_entries",
                to="administration.term",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_sessions",
                to="administration.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_sessions",
                to="administration.term",
            ),
        ),
        migrations.AlterField(
            model_name="assessmententry",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
