# Generated by Django 5.2.11 on 2026-08-20 23:48

from django.db import migrations

def populate_term_and_session(apps, schema_editor):
    AssessmentEntry = apps.get_model('examination', 'AssessmentEntry')
    AssessmentSession = apps.get_model('examination', 'AssessmentSession')
    TermResult = apps.get_model('examination', 'TermResult')
    Term = apps.get_model('administration', 'Term')
    
    # 1. Update AssessmentSession using term dates
    for session in AssessmentSession.objects.all():
        terms = Term.objects.filter(
            start_date__lte=session.start_date,
            end_date__gte=session.start_date
        )
        if terms.exists():
            term = terms.first()
            session.term = term
            session.academic_year = term.academic_year
            session.save()
            
    # 2. Update AssessmentEntry using TermResult logic
    # To honor user request, we use existing relationships first (enrollment -> academic year, term result -> term).
    for entry in AssessmentEntry.objects.filter(term__isnull=True):
        enrollment = entry.student
        if enrollment:
            entry.academic_year = enrollment.academic_year
            
            # Find the matching term result where this score was used.
            # TermResult has student, academic_year, term. We can check if the score exists in its SubjectResults.
            term_results = TermResult.objects.filter(
                student=enrollment.student,
                academic_year=enrollment.academic_year
            )
            found_term = None
            for tr in term_results:
                # Check if this term result consumed this entry
                has_score = tr.subject_results.filter(
                    subject_id=entry.subject_id,
                    assessment_scores__component=entry.component,
                    assessment_scores__score=entry.score
                ).exists()
                if has_score:
                    found_term = tr.term
                    break
            
            if found_term:
                entry.term = found_term
            else:
                # Fallback to date inference only if we can't find a TermResult association
                terms = Term.objects.filter(
                    start_date__lte=entry.entered_at.date(),
                    end_date__gte=entry.entered_at.date(),
                    academic_year=enrollment.academic_year
                )
                if terms.exists():
                    entry.term = terms.first()
                    
            # Try to associate with an AssessmentSession if one exists for the class/term
            if not entry.session and entry.term:
                sessions = AssessmentSession.objects.filter(
                    term=entry.term,
                    classrooms=enrollment.classroom,
                    assessment_type=entry.component.name.upper() # Best effort map
                )
                if sessions.exists():
                    entry.session = sessions.first()
        
        # Set status/source if score is None
        if entry.score is None:
            entry.status = "MISSING"
        else:
            entry.status = "COMPLETE"
        
        entry.source = "MANUAL"
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0011_add_term_and_status_to_assessment"),
    ]

    operations = [
        migrations.RunPython(populate_term_and_session, reverse_code=migrations.RunPython.noop),
    ]
