# Generated by Django 5.2.11 on 2026-08-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0013_add_status_to_subject_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotiondecision",
            name="structured_reasons",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured decision payload for programmatic checks",
            ),
        ),
        migrations.AlterField(
            model_name="promotiondecision",
            name="reasons",
            field=models.TextField(
                blank=True,
                help_text="Automated human-readable reasons for this decision",
            ),
        ),
    ]
