# Generated by Django 5.2.11 on 2026-08-21 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_schoolsection"),
        ("examination", "0016_add_lifecycle_fields_to_cumulative_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="cumulativeresult",
            name="policy_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the cumulative policy at the time of computation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cumulativesubjectresult",
            name="annual_subject_results",
            field=models.ManyToManyField(
                blank=True,
                related_name="cumulative_subject_results",
                to="examination.annualsubjectresult",
            ),
        ),
        migrations.CreateModel(
            name="AnnualWeightConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight percentage (e.g. 30.00 for 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "cumulative_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_weights",
                        to="examination.cumulativepolicy",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        help_text="The grade level this weight applies to (e.g. JSS 1)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.gradelevel",
                    ),
                ),
            ],
            options={
                "unique_together": {("cumulative_policy", "grade_level")},
            },
        ),
    ]
