# Generated by Django 5.2.11 on 2026-08-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_schoolsection"),
        ("examination", "0017_stage8_cumulative_improvements"),
    ]

    operations = [
        migrations.AddField(
            model_name="academictranscript",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="academictranscript",
            name="serial_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="academictranscript",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("OFFICIAL", "Official"),
                    ("REVOKED", "Revoked"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="academictranscript",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="academictranscript",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_transcripts",
                to="academic.student",
            ),
        ),
    ]
