# Generated by Django 5.2.11 on 2026-08-21 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0018_stage9_transcript_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="academictranscript",
            name="status",
            field=models.CharField(
                choices=[
                    ("CURRENT", "Current"),
                    ("SUPERSEDED", "Superseded"),
                    ("REVOKED", "Revoked"),
                ],
                default="CURRENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("GENERATING", "Generating"),
                    ("CURRENT", "Current"),
                    ("SUPERSEDED", "Superseded"),
                    ("FAILED", "Failed"),
                ],
                default="CURRENT",
                help_text="Generation status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="term_result",
            field=models.ForeignKey(
                help_text="Associated term result",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="examination.termresult",
            ),
        ),
    ]
