# Generated by Django 5.2.11 on 2026-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0019_stage9_report_card_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmententry",
            name="source_reference",
            field=models.CharField(
                blank=True,
                help_text="External reference ID (e.g. CBT Attempt ID) for traceability.",
                max_length=100,
                null=True,
            ),
        ),
    ]
