# Generated by Django 5.2.11 on 2026-08-21 01:08

from django.db import migrations, models


def ensure_source_reference_unique_index(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS "
            '"examination_assessmententry_source_reference_repair_uniq" '
            'ON "examination_assessmententry" ("source_reference")'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0020_stage10_assessment_entry_traceability"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_source_reference_unique_index, migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="assessmententry",
                    name="source_reference",
                    field=models.CharField(
                        blank=True,
                        help_text="External reference ID (e.g. CBT Attempt ID) for traceability.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
