# Generated by Django 5.2.11 on 2026-08-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0020_stage10_assessment_entry_traceability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmententry",
            name="source_reference",
            field=models.CharField(
                blank=True,
                help_text="External reference ID (e.g. CBT Attempt ID) for traceability.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
