# Generated by Django 5.2.11 on 2026-08-31 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0022_repair_assessmententry_source_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("AFFECTIVE", "Affective"),
                            ("PSYCHOMOTOR", "Psychomotor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRE_PRIMARY", "Pre-Primary Education"),
                            ("PRIMARY", "Primary Education"),
                            ("JSS", "Junior Secondary School"),
                            ("SSS", "Senior Secondary School"),
                        ],
                        help_text="If null, applies school-wide",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["domain", "order", "name"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="examination_domain_927a49_idx"
                    ),
                    models.Index(
                        fields=["section"], name="examination_section_3440c6_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="examination_is_acti_2c3fc9_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("domain", "section", "name"),
                        name="unique_active_trait_name_per_domain_section",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentBehavioralRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavioral_ratings",
                        to="examination.termresult",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_ratings",
                        to="examination.behavioraltrait",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term_result", "trait"),
                        name="unique_trait_rating_per_term_result",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="valid_behavioral_rating_range",
                    ),
                ],
            },
        ),
    ]
