# Generated by Django 5.2.11 on 2026-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0023_behavioraltrait_studentbehavioralrating"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="behavioraltrait",
            name="unique_active_trait_name_per_domain_section",
        ),
        migrations.AddConstraint(
            model_name="behavioraltrait",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("section__isnull", False)),
                fields=("domain", "section", "name"),
                name="unique_active_trait_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="behavioraltrait",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("section__isnull", True)),
                fields=("domain", "name"),
                name="unique_active_trait_schoolwide",
            ),
        ),
    ]
