# Generated by Django 5.2.11 on 2026-09-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "examination",
            "0024_remove_behavioraltrait_unique_active_trait_name_per_domain_section_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="termresult",
            name="grading_scale_snapshot",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot of the complete grading scheme rules at computation time",
            ),
        ),
        migrations.AlterField(
            model_name="termresult",
            name="class_teacher_remarks",
            field=models.TextField(
                blank=True, help_text="Class teacher's assessment/remarks", null=True
            ),
        ),
        migrations.AlterField(
            model_name="termresult",
            name="principal_remarks",
            field=models.TextField(
                blank=True, help_text="Principal's assessment/remarks", null=True
            ),
        ),
    ]
