# Generated by Django on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0017_alter_gradelevel_system_code"),
        ("examination", "0025_termresult_grading_scale_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.teacher",
            ),
        ),
    ]
