from django.db import connection, models, transaction
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Sum
from decimal import Decimal
from administration.models import Term, AcademicYear
from academic.models import GradeLevel, ClassRoom
from django.conf import settings
from academic.models import Teacher, Student


class PaymentStatus(models.TextChoices):
    PENDING = "Pending", "Pending"
    COMPLETED = "Completed", "Completed"
    CANCELLED = "Cancelled", "Cancelled"


class PaymentThrough(models.TextChoices):
    CASH = "Cash", "Cash"
    BANK_TRANSFER = "Bank Transfer", "Bank Transfer"
    CHEQUE = "Cheque", "Cheque"
    MOBILE_MONEY = "Mobile Money", "Mobile Money"
    CARD = "Card", "Card"


class FeeType(models.TextChoices):
    TUITION = "Tuition", "Tuition"
    ADMISSION = "Admission", "Admission"
    TRANSPORT = "Transport", "Transport"
    MEALS = "Meals", "Meals"
    EXAM = "Exam", "Exam"
    LIBRARY = "Library", "Library"
    LABORATORY = "Laboratory", "Laboratory"
    SPORTS = "Sports", "Sports"
    MAINTENANCE = "Maintenance", "Maintenance"
    BOOKS = "Books", "Books"
    UNIFORM = "Uniform", "Uniform"
    OTHER = "Other", "Other"


# ============================================================================
# OPTIONAL SERVICES MODELS
# ============================================================================

class OptionalService(models.Model):
    """
    Represents an optional service offered by the school, such as Transport,
    Meals, or Clubs. Students can subscribe to these services.
    """
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    fee_type = models.CharField(
        max_length=50,
        choices=FeeType.choices,
        help_text="The type of fee generated by this service"
    )
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.get_fee_type_display()})"


class ServiceSubscription(models.Model):
    """
    Tracks which students are subscribed to which optional services.
    """
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='service_subscriptions'
    )
    service = models.ForeignKey(
        OptionalService,
        on_delete=models.CASCADE,
        related_name='subscriptions'
    )
    subscribed_on = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ['student', 'service']
        ordering = ['-subscribed_on']

    def __str__(self):
        return f"{self.student.full_name} - {self.service.name}"


# ============================================================================
# FEE STRUCTURE MODELS
# ============================================================================

class FeeStructure(models.Model):
    """
    Defines fee templates/structures for the school.
    These are the fee "types" that can be assigned to students.
    """
    name = models.CharField(max_length=255)
    fee_type = models.CharField(
        max_length=50,
        choices=FeeType.choices,
        default=FeeType.TUITION
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Standard amount for this fee"
    )

    # Scope - defines who this fee applies to
    academic_year = models.ForeignKey(
        AcademicYear,
        on_delete=models.CASCADE,
        related_name='fee_structures'
    )
    term = models.ForeignKey(
        Term,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='fee_structures',
        help_text="Leave blank to apply to all terms in the academic year"
    )
    grade_levels = models.ManyToManyField(
        GradeLevel,
        blank=True,
        related_name='fee_structures',
        help_text="Leave blank to apply to all grade levels"
    )
    classrooms = models.ManyToManyField(
        ClassRoom,
        blank=True,
        related_name='fee_structures',
        help_text="Leave blank to apply to all classrooms in the selected grade levels"
    )

    # Optional Service link
    optional_service = models.ForeignKey(
        OptionalService,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='fee_structures',
        help_text="If linked to a service, this fee will be auto-assigned to subscribed students"
    )

    # Fee properties
    is_mandatory = models.BooleanField(
        default=True,
        help_text="Mandatory fees are auto-assigned to all applicable students"
    )
    due_date = models.DateField(
        null=True,
        blank=True,
        help_text="Due date for this fee"
    )

    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_fee_structures'
    )

    class Meta:
        ordering = ['-academic_year', 'term', 'fee_type']
        indexes = [
            models.Index(fields=['academic_year', 'term']),
            models.Index(fields=['is_mandatory']),
        ]

    def __str__(self):
        scope = []

        # Get grade levels
        try:
            grade_count = self.grade_levels.count()
            if grade_count > 0:
                if grade_count <= 2:
                    scope.append(", ".join(g.alias or g.default_name for g in self.grade_levels.all()))
                else:
                    scope.append(f"{grade_count} grades")
        except:
            pass

        # Get classrooms
        try:
            class_count = self.classrooms.count()
            if class_count > 0:
                if class_count <= 2:
                    scope.append(", ".join(c.name for c in self.classrooms.all()))
                else:
                    scope.append(f"{class_count} classes")
        except:
            pass

        if self.term:
            scope.append(self.term.name)
        else:
            scope.append("All Terms")

        scope_str = " - ".join(scope) if scope else "All Students"
        return f"{self.name} ({scope_str}) - ₦{self.amount:,.2f}"

    def clean(self):
        if self.amount <= 0:
            raise ValidationError("Amount must be a positive value.")

        # Validate due date is within academic year
        if self.due_date:
            if self.academic_year.start_date and self.due_date < self.academic_year.start_date:
                raise ValidationError("Due date cannot be before academic year start date.")
            if self.academic_year.end_date and self.due_date > self.academic_year.end_date:
                raise ValidationError("Due date cannot be after academic year end date.")

        # Validate due date is within term if term is specified
        if self.term and self.due_date:
            if self.due_date < self.term.start_date or self.due_date > self.term.end_date:
                raise ValidationError("Due date must be within the selected term dates.")

    def applies_to_student(self, student, term=None):
        """Check if this fee structure applies to a given student."""
        # Check grade levels
        grade_levels_list = list(self.grade_levels.all())
        if grade_levels_list:
            student_grade = student.classroom.grade_level if (student.classroom and hasattr(student.classroom, "grade_level")) else None
            if not student_grade or student_grade not in grade_levels_list:
                return False

        # Check classrooms
        classrooms_list = list(self.classrooms.all())
        if classrooms_list:
            if not student.classroom or student.classroom not in classrooms_list:
                return False

        # Check term
        if self.term and term and self.term != term:
            return False

        return True

    def auto_assign_to_students(self, term=None):
        """
        Auto-assign this fee to applicable students.
        For mandatory fees, assigns to all applicable students.
        For optional fees linked to a service, assigns to subscribed students.
        """
        from finance.services.fee_assignment_service import FeeAssignmentService

        return FeeAssignmentService.assign_fee(fee_structure=self, term=term)


class StudentFeeAssignment(models.Model):
    """
    Links students to specific fees they owe.
    Tracks payment progress for each fee.
    This replaces the old DebtRecord model with better granularity.
    """
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='fee_assignments'
    )
    fee_structure = models.ForeignKey(
        FeeStructure,
        on_delete=models.CASCADE,
        related_name='student_assignments'
    )
    term = models.ForeignKey(
        Term,
        on_delete=models.CASCADE,
        related_name='fee_assignments'
    )

    # Financial tracking
    amount_owed = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Can be different from fee_structure.amount for discounts/adjustments"
    )
    amount_paid = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0.00')
    )

    # Status flags
    is_waived = models.BooleanField(
        default=False,
        help_text="Waived fees (scholarships, etc.) don't need to be paid"
    )
    waived_reason = models.TextField(blank=True, null=True)
    waived_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='waived_fees'
    )
    waived_date = models.DateTimeField(null=True, blank=True)

    # Metadata
    assigned_date = models.DateTimeField(auto_now_add=True)
    last_payment_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('student', 'fee_structure', 'term')
        ordering = ['-term', 'fee_structure__fee_type', 'student']
        constraints = [
            models.CheckConstraint(condition=models.Q(amount_owed__gte=0), name='finance_assignment_owed_nonnegative'),
            models.CheckConstraint(condition=models.Q(amount_paid__gte=0), name='finance_assignment_paid_nonnegative'),
            models.CheckConstraint(condition=models.Q(amount_paid__lte=models.F('amount_owed')), name='finance_assignment_paid_lte_owed'),
        ]
        indexes = [
            models.Index(fields=['student', 'term']),
            models.Index(fields=['is_waived']),
        ]

    def __str__(self):
        return f"{self.student.full_name} - {self.fee_structure.name} ({self.term.name})"

    @property
    def balance(self):
        """Remaining amount to be paid."""
        if self.is_waived:
            return Decimal('0.00')
        return max(Decimal('0.00'), self.amount_owed - self.amount_paid)

    @property
    def is_fully_paid(self):
        """Check if the fee is fully paid."""
        return self.balance == Decimal('0.00')

    @property
    def payment_status(self):
        """Return payment status: Paid, Partial, Unpaid, Waived."""
        if self.is_waived:
            return "Waived"
        if self.is_fully_paid:
            return "Paid"
        if self.amount_paid > 0:
            return "Partial"
        return "Unpaid"

    def clean(self):
        if self.amount_owed < 0:
            raise ValidationError("Amount owed cannot be negative.")
        if self.amount_paid < 0:
            raise ValidationError("Amount paid cannot be negative.")
        if self.amount_paid > self.amount_owed:
            raise ValidationError("Amount paid cannot exceed amount owed.")

    def apply_payment(self, amount):
        """
        Apply a payment to this fee assignment.
        Returns the amount actually applied.
        """
        amount = Decimal(str(amount))

        if amount <= 0:
            raise ValueError("Payment amount must be positive.")

        if self.is_waived:
            raise ValueError("Cannot apply payment to waived fee.")

        # Calculate how much can be applied
        applicable_amount = min(amount, self.balance)

        if applicable_amount > 0:
            self.amount_paid += applicable_amount
            self.last_payment_date = timezone.now()
            self.save()

        return applicable_amount

    def waive_fee(self, reason, waived_by):
        """Waive this fee (scholarship, discount, etc.)."""
        self.is_waived = True
        self.waived_reason = reason
        self.waived_by = waived_by
        self.waived_date = timezone.now()
        self.save()

    def adjust_amount(self, new_amount, reason=None):
        """Adjust the amount owed (for discounts, penalties, etc.)."""
        new_amount = Decimal(str(new_amount))

        if new_amount < 0:
            raise ValueError("New amount cannot be negative.")

        if new_amount < self.amount_paid:
            raise ValueError("New amount cannot be less than amount already paid.")

        old_amount = self.amount_owed
        self.amount_owed = new_amount
        self.save()

        # Log the adjustment
        FeeAdjustment.objects.create(
            fee_assignment=self,
            old_amount=old_amount,
            new_amount=new_amount,
            reason=reason or "Manual adjustment"
        )


class FeeAdjustment(models.Model):
    """Track all fee adjustments for audit purposes."""
    fee_assignment = models.ForeignKey(
        StudentFeeAssignment,
        on_delete=models.CASCADE,
        related_name='adjustments'
    )
    old_amount = models.DecimalField(max_digits=10, decimal_places=2)
    new_amount = models.DecimalField(max_digits=10, decimal_places=2)
    reason = models.TextField()
    adjusted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    adjusted_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-adjusted_date']

    def __str__(self):
        return f"{self.fee_assignment} adjusted from ₦{self.old_amount} to ₦{self.new_amount}"


# ============================================================================
# RECEIPT AND PAYMENT MODELS
# ============================================================================

class Receipt(models.Model):
    """
    Records incoming payments from students/parents.
    Updated to support fee assignment tracking.
    """
    receipt_number = models.IntegerField(unique=True, blank=True, null=True)
    date = models.DateField(auto_now_add=True)
    payer = models.CharField(max_length=255, default="Unknown")
    student = models.ForeignKey(
        Student,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='receipts'
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid_through = models.CharField(
        max_length=20,
        choices=PaymentThrough.choices,
        default=PaymentThrough.CASH
    )
    term = models.ForeignKey(
        Term,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='receipts'
    )
    payment_date = models.DateField(default=timezone.now)
    reference_number = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text="External reference number (bank ref, mobile money ref, etc.)"
    )
    status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.COMPLETED
    )
    received_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='received_receipts'
    )
    remarks = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-date', '-receipt_number']
        constraints = [
            models.CheckConstraint(condition=models.Q(amount__gt=0), name='finance_receipt_amount_positive'),
        ]
        indexes = [
            models.Index(fields=['student', 'term']),
            models.Index(fields=['receipt_number']),
            models.Index(fields=['date']),
        ]

    def __str__(self):
        return f"Receipt #{self.receipt_number} - {self.payer} - ₦{self.amount:,.2f}"

    def clean(self):
        if self.amount <= 0:
            raise ValidationError("Amount must be a positive value.")

    def save(self, *args, **kwargs):
        if self.receipt_number:
            return super().save(*args, **kwargs)

        # Lock a stable PostgreSQL advisory key because an empty queryset has
        # no row for select_for_update() to lock.
        with transaction.atomic():
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT pg_advisory_xact_lock(hashtext(%s))",
                    [f"{connection.schema_name}:finance:receipt-number"],
                )
            if not self.receipt_number:
                last_receipt = Receipt.objects.order_by("-receipt_number").first()
                self.receipt_number = (
                    (last_receipt.receipt_number + 1) if last_receipt else 1
                )
            return super().save(*args, **kwargs)

    @transaction.atomic
    def delete(self, *args, **kwargs):
        locked_receipt = Receipt.objects.select_for_update().get(pk=self.pk)
        assignment_ids = list(
            locked_receipt.fee_allocations.order_by()
            .values_list("fee_assignment_id", flat=True)
            .distinct()
        )
        assignments = list(
            StudentFeeAssignment.objects.select_for_update()
            .filter(pk__in=assignment_ids)
            .order_by("pk")
        )
        for assignment in assignments:
            allocated = locked_receipt.fee_allocations.filter(
                fee_assignment=assignment
            ).aggregate(total=Sum("amount"))["total"] or Decimal("0.00")
            assignment.amount_paid -= allocated
            assignment.full_clean()
            assignment.save(update_fields=("amount_paid",))
        return super().delete(*args, **kwargs)

    @property
    def allocated_amount(self):
        """Amount allocated to specific fee assignments."""
        return self.fee_allocations.aggregate(
            total=Sum('amount')
        )['total'] or Decimal('0.00')

    @property
    def unallocated_amount(self):
        """Amount not yet allocated to any fee."""
        return self.amount - self.allocated_amount


class FeePaymentAllocation(models.Model):
    """
    Links receipts to specific fee assignments.
    Allows one receipt to pay multiple fees, or multiple receipts to pay one fee.
    This replaces the old PaymentRecord model.
    """
    receipt = models.ForeignKey(
        Receipt,
        on_delete=models.CASCADE,
        related_name='fee_allocations'
    )
    fee_assignment = models.ForeignKey(
        StudentFeeAssignment,
        on_delete=models.CASCADE,
        related_name='payment_allocations'
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Amount of this receipt allocated to this fee"
    )
    allocated_date = models.DateTimeField(auto_now_add=True)
    allocated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['-allocated_date']
        constraints = [
            models.CheckConstraint(condition=models.Q(amount__gt=0), name='finance_allocation_amount_positive'),
        ]
        indexes = [
            models.Index(fields=['receipt', 'fee_assignment']),
        ]

    def __str__(self):
        return f"Receipt #{self.receipt.receipt_number} → {self.fee_assignment} (₦{self.amount:,.2f})"

    def clean(self):
        if self.amount <= 0:
            raise ValidationError("Allocation amount must be positive.")

        if self.amount > self.fee_assignment.balance:
            raise ValidationError(
                f"Cannot allocate ₦{self.amount} - fee balance is only ₦{self.fee_assignment.balance}"
            )

        # Check receipt doesn't over-allocate
        current_allocated = self.receipt.fee_allocations.exclude(
            pk=self.pk
        ).aggregate(total=Sum('amount'))['total'] or Decimal('0.00')

        if current_allocated + self.amount > self.receipt.amount:
            raise ValidationError(
                f"Cannot allocate ₦{self.amount} - only ₦{self.receipt.amount - current_allocated} remaining"
            )

    @transaction.atomic
    def save(self, *args, **kwargs):
        if self.pk:
            original = FeePaymentAllocation.objects.get(pk=self.pk)
            immutable = ("receipt_id", "fee_assignment_id", "amount")
            if any(getattr(original, field) != getattr(self, field) for field in immutable):
                raise ValidationError("Posted fee allocations are immutable; reverse and recreate the allocation.")
            return super().save(*args, **kwargs)

        receipt = Receipt.objects.select_for_update().get(pk=self.receipt_id)
        assignment = StudentFeeAssignment.objects.select_for_update().get(pk=self.fee_assignment_id)
        self.receipt = receipt
        self.fee_assignment = assignment

        if receipt.student_id and receipt.student_id != assignment.student_id:
            raise ValidationError("A receipt can only be allocated to fees for the same student.")

        self.full_clean()
        result = super().save(*args, **kwargs)
        assignment.amount_paid += self.amount
        assignment.last_payment_date = timezone.now()
        assignment.full_clean()
        assignment.save(update_fields=("amount_paid", "last_payment_date"))
        return result

    @transaction.atomic
    def delete(self, *args, **kwargs):
        allocation = FeePaymentAllocation.objects.select_for_update().get(pk=self.pk)
        assignment = StudentFeeAssignment.objects.select_for_update().get(
            pk=allocation.fee_assignment_id
        )
        assignment.amount_paid -= allocation.amount
        assignment.full_clean()
        assignment.save(update_fields=("amount_paid",))
        return super().delete(*args, **kwargs)


# ============================================================================
# OUTGOING PAYMENT MODEL (for school expenses)
# ============================================================================

class PaymentCategory(models.Model):
    """Categories for outgoing payments/expenses."""
    name = models.CharField(max_length=255)
    abbr = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Payment Categories"

    def __str__(self):
        return self.name


class Payment(models.Model):
    """Outgoing payments (salaries, utilities, supplies, etc.)."""
    payment_number = models.IntegerField(
        unique=True,
        blank=True,
        null=True,
        db_index=True
    )
    date = models.DateField(auto_now_add=True)
    paid_to = models.CharField(max_length=255)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="payments",
        help_text="If payment is to a system user (teacher, accountant, etc.)"
    )
    category = models.ForeignKey(
        PaymentCategory,
        on_delete=models.SET_NULL,
        null=True,
        related_name='payments'
    )
    paid_through = models.CharField(
        max_length=20,
        choices=PaymentThrough.choices,
        default=PaymentThrough.CASH
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    reference_number = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text="Cheque number, transfer reference, etc."
    )
    description = models.TextField(blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.COMPLETED
    )
    paid_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='processed_payments'
    )

    class Meta:
        ordering = ['-date', '-payment_number']
        constraints = [
            models.CheckConstraint(condition=models.Q(amount__gt=0), name='finance_payment_amount_positive'),
        ]
        indexes = [
            models.Index(fields=['date']),
            models.Index(fields=['category']),
        ]

    def __str__(self):
        return f"Payment #{self.payment_number} - {self.paid_to} - ₦{self.amount:,.2f}"

    def clean(self):
        if self.amount <= 0:
            raise ValidationError("Amount must be a positive value.")

    def save(self, *args, **kwargs):
        if self.payment_number:
            return super().save(*args, **kwargs)

        with transaction.atomic():
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT pg_advisory_xact_lock(hashtext(%s))",
                    [f"{connection.schema_name}:finance:payment-number"],
                )
            if not self.payment_number:
                last_payment = Payment.objects.order_by("-payment_number").first()
                self.payment_number = (
                    (last_payment.payment_number + 1) if last_payment else 1
                )
            return super().save(*args, **kwargs)


# ============================================================================
# REMINDER SYSTEM
# ============================================================================

class ReminderSetting(models.Model):
    name = models.CharField(max_length=255)
    # If fee_structure is null, this is a default rule applying to all fees.
    # If set, it applies only to that specific fee.
    fee_structure = models.ForeignKey('FeeStructure', null=True, blank=True, on_delete=models.CASCADE, related_name='reminder_settings')
    days_before_due = models.IntegerField(help_text="Positive for days before due date, negative for overdue days.")
    is_active = models.BooleanField(default=False)  # User requested disabled by default
    message_template = models.TextField(help_text="Variables available: {{student_name}}, {{fee_name}}, {{amount_owed}}, {{due_date}}")
    partial_payment_template = models.TextField(help_text="Variables available: {{student_name}}, {{fee_name}}, {{balance}}, {{amount_paid}}, {{due_date}}", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.days_before_due} days)"

# ============================================================================
# AUDIT LOG
# ============================================================================

class AuditAction(models.TextChoices):
    FEE_ASSIGNED = "Fee Assigned", "Fee Assigned"
    BULK_FEE_ASSIGNED = "Bulk Fee Assigned", "Bulk Fee Assigned"
    FEE_WAIVED = "Fee Waived", "Fee Waived"
    AMOUNT_ADJUSTED = "Amount Adjusted", "Amount Adjusted"
    PAYMENT_RECORDED = "Payment Recorded", "Payment Recorded"
    PAYMENT_REVERSED = "Payment Reversed", "Payment Reversed"
    SERVICE_SUBSCRIBED = "Service Subscribed", "Service Subscribed"
    SERVICE_UNSUBSCRIBED = "Service Unsubscribed", "Service Unsubscribed"
    OTHER = "Other", "Other"

class FinanceAuditLog(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='finance_audit_logs')
    action = models.CharField(max_length=50, choices=AuditAction.choices)
    target_student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True, blank=True, related_name='finance_audit_logs')
    description = models.TextField(help_text="Human readable description of the action taken.")
    metadata = models.JSONField(default=dict, blank=True, help_text="Raw data payload for debugging (e.g. original vs new amount).")

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.timestamp.strftime('%Y-%m-%d %H:%M:%S')} - {self.action} by {self.user.email if self.user else 'System'}"
