# Generated by Django 5.2.11 on 2026-08-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0005_allocatedsubject_is_mandatory"),
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "week_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Curriculum week number (e.g. 1, 2, 3...)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Brief summary of the lesson concepts"
                    ),
                ),
                (
                    "learning_objectives",
                    models.TextField(
                        blank=True, help_text="Key takeaways students should understand"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_topics",
                        to="administration.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_topics",
                        to="academic.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_topics",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_topics",
                        to="academic.teacher",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_topics",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year", "week_number", "title"],
            },
        ),
        migrations.CreateModel(
            name="LessonMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("text", "Typed Note / Lecture Text"),
                            ("document", "Document (PDF / Word)"),
                            ("link", "External Reference URL"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text content used for AI context",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ai_tutor/materials/"
                    ),
                ),
                ("external_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="ai_tutor.lessontopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAvatarSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar_style",
                    models.CharField(
                        choices=[
                            ("photo_animated", "Realistic Photo Avatar"),
                            ("illustrated", "Illustrated Academic Persona"),
                            ("minimal_glow", "Minimalist Soundwave & Glow"),
                        ],
                        default="photo_animated",
                        max_length=30,
                    ),
                ),
                (
                    "teaching_tone",
                    models.CharField(
                        choices=[
                            ("encouraging", "Warm & Encouraging (Praise-oriented)"),
                            (
                                "socratic",
                                "Socratic & Inquisitive (Asks guiding questions)",
                            ),
                            (
                                "step_by_step",
                                "Structured & Analytical (Step-by-step breakdowns)",
                            ),
                            (
                                "simplified",
                                "Simple & Intuitive (Rich analogies for younger pupils)",
                            ),
                        ],
                        default="socratic",
                        max_length=30,
                    ),
                ),
                (
                    "custom_system_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Custom behavioral guidelines from the teacher (e.g., 'Never give direct solutions to algebra problems, guide them through factoring first.')",
                    ),
                ),
                ("is_ai_tutor_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_avatar_setting",
                        to="academic.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Tutoring Session", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tutor_sessions",
                        to="ai_tutor.lessontopic",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tutor_sessions",
                        to="academic.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tutor_sessions",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tutor_sessions",
                        to="academic.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("assistant", "Teacher AI"),
                            ("system", "System Context"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "topic_referenced",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_tutor.tutorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lessontopic",
            index=models.Index(
                fields=["classroom", "subject", "week_number"],
                name="ai_tutor_le_classro_8163f7_idx",
            ),
        ),
    ]
