# Generated by Django 5.2.11 on 2026-08-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_alter_studentclassenrollment_student_and_more"),
        ("ai_tutor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorSessionInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("misconceptions", models.JSONField(blank=True, default=list)),
                ("concepts_struggled_with", models.JSONField(blank=True, default=list)),
                ("concepts_mastered", models.JSONField(blank=True, default=list)),
                ("follow_up_recommended", models.BooleanField(default=False)),
                ("teacher_attention_required", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="lessonmaterial",
            name="lesson_topic",
        ),
        migrations.RemoveField(
            model_name="lessontopic",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="lessontopic",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="lessontopic",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="lessontopic",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="lessontopic",
            name="term",
        ),
        migrations.RemoveField(
            model_name="tutorsession",
            name="lesson_topic",
        ),
        migrations.RemoveField(
            model_name="tutormessage",
            name="topic_referenced",
        ),
        migrations.AddField(
            model_name="teacheravatarsetting",
            name="allow_direct_answers",
            field=models.BooleanField(
                default=False,
                help_text="Controls whether the tutor is allowed to provide direct answers versus guiding students through reasoning.",
            ),
        ),
        migrations.AddField(
            model_name="tutormessage",
            name="learning_objective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutor_messages",
                to="academic.learningobjective",
            ),
        ),
        migrations.AddField(
            model_name="tutorsession",
            name="curriculum_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_tutor_sessions",
                to="academic.curriculumtopic",
            ),
        ),
        migrations.AddField(
            model_name="tutorsession",
            name="learning_objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="ai_tutor_sessions",
                to="academic.learningobjective",
            ),
        ),
        migrations.AddField(
            model_name="tutorsession",
            name="lesson_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_tutor_sessions",
                to="academic.lessondelivery",
            ),
        ),
        migrations.AddField(
            model_name="tutorsession",
            name="lesson_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_tutor_sessions",
                to="academic.lessonplan",
            ),
        ),
        migrations.AlterField(
            model_name="teacheravatarsetting",
            name="custom_system_instructions",
            field=models.TextField(
                blank=True, help_text="Custom behavioral guidelines from the teacher."
            ),
        ),
        migrations.AlterField(
            model_name="tutorsession",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_tutor_sessions",
                to="academic.subject",
            ),
        ),
        migrations.AlterField(
            model_name="tutorsession",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_tutor_sessions",
                to="academic.teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="tutormessage",
            index=models.Index(
                fields=["session", "created_at"], name="ai_tutor_tu_session_94de0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tutorsession",
            index=models.Index(
                fields=["student", "subject", "-updated_at"],
                name="ai_tutor_tu_student_7a2324_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tutorsession",
            index=models.Index(
                fields=["teacher", "-updated_at"], name="ai_tutor_tu_teacher_94d66d_idx"
            ),
        ),
        migrations.AddField(
            model_name="tutorsessioninsight",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insight",
                to="ai_tutor.tutorsession",
            ),
        ),
        migrations.DeleteModel(
            name="LessonMaterial",
        ),
        migrations.DeleteModel(
            name="LessonTopic",
        ),
    ]
