# Generated by Django 5.2.11 on 2026-02-20 10:38

import academic.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated (e.g., ADM/2025/001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("documents_pending", "Documents Pending"),
                            ("exam_scheduled", "Exam Scheduled"),
                            ("exam_completed", "Exam Completed"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                            ("enrolled", "Enrolled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "state_of_origin",
                    models.CharField(
                        help_text="Nigerian state of origin", max_length=100
                    ),
                ),
                (
                    "lga",
                    models.CharField(help_text="Local Government Area", max_length=100),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Islam", "Islam"),
                            ("Christian", "Christian"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True, help_text="e.g., O+, A-, AB+", max_length=5
                    ),
                ),
                ("address", models.TextField(help_text="Residential address")),
                ("city", models.CharField(max_length=100)),
                ("parent_first_name", models.CharField(max_length=100)),
                ("parent_last_name", models.CharField(max_length=100)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(max_length=15)),
                ("parent_occupation", models.CharField(blank=True, max_length=100)),
                (
                    "parent_relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        default="father",
                        max_length=50,
                    ),
                ),
                (
                    "alt_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Alternative emergency contact",
                        max_length=200,
                    ),
                ),
                ("alt_contact_phone", models.CharField(blank=True, max_length=15)),
                (
                    "alt_contact_relationship",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True,
                        help_text="Name of previous school (if any)",
                        max_length=255,
                    ),
                ),
                (
                    "previous_class",
                    models.CharField(
                        blank=True, help_text="Last class attended", max_length=100
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Any medical conditions or allergies"
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(
                        blank=True, help_text="Any special educational needs"
                    ),
                ),
                ("application_fee_paid", models.BooleanField(default=False)),
                (
                    "application_fee_payment_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("exam_fee_paid", models.BooleanField(default=False)),
                ("exam_fee_payment_date", models.DateTimeField(blank=True, null=True)),
                ("acceptance_fee_paid", models.BooleanField(default=False)),
                (
                    "acceptance_fee_payment_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "acceptance_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline to accept offer (calculated from approval date)",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from admin review"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if applicable)"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When parent accepted the offer",
                        null=True,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tracking_token",
                    models.CharField(
                        editable=False,
                        help_text="Secure token for external application tracking",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission Application",
                "verbose_name_plural": "Admission Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("entrance_exam", "Entrance Examination"),
                            ("interview", "Interview"),
                            ("aptitude_test", "Aptitude Test"),
                            ("screening", "Screening Test"),
                            ("oral_test", "Oral Test"),
                            ("practical", "Practical Assessment"),
                            ("psychometric", "Psychometric Test"),
                            ("portfolio_review", "Portfolio Review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Duration in minutes"
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall score achieved",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Maximum possible score",
                        max_digits=5,
                    ),
                ),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Minimum score to pass",
                        max_digits=5,
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student passed this assessment",
                    ),
                ),
                (
                    "assessor_notes",
                    models.TextField(
                        blank=True, help_text="General notes from assessor"
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        blank=True, help_text="Student's strengths observed"
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(blank=True, help_text="Areas needing improvement"),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("highly_recommended", "Highly Recommended"),
                            ("recommended", "Recommended"),
                            ("conditional", "Conditional"),
                            ("not_recommended", "Not Recommended"),
                        ],
                        help_text="Overall recommendation",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instructions for this assessment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admission Assessment",
                "verbose_name_plural": "Admission Assessments",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("passport_photo", "Passport Photograph"),
                            ("previous_results", "Previous School Results"),
                            ("transfer_certificate", "Transfer Certificate"),
                            ("medical_records", "Medical Records"),
                            ("immunization_card", "Immunization Card"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="admission_documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Has admin verified this document?"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Admission Document",
                "verbose_name_plural": "Admission Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionFeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee to submit application",
                        max_digits=10,
                    ),
                ),
                (
                    "application_fee_required",
                    models.BooleanField(
                        default=True, help_text="Must pay application fee to submit"
                    ),
                ),
                (
                    "entrance_exam_required",
                    models.BooleanField(
                        default=False,
                        help_text="Does this class require entrance exam?",
                    ),
                ),
                (
                    "entrance_exam_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee to take entrance exam",
                        max_digits=10,
                    ),
                ),
                (
                    "entrance_exam_pass_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum score to pass entrance exam (percentage)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "interview_required",
                    models.BooleanField(
                        default=False, help_text="Does this class require interview?"
                    ),
                ),
                (
                    "acceptance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee to accept admission offer",
                        max_digits=10,
                    ),
                ),
                (
                    "acceptance_fee_required",
                    models.BooleanField(
                        default=True,
                        help_text="Must pay acceptance fee to accept offer",
                    ),
                ),
                (
                    "acceptance_fee_is_part_of_tuition",
                    models.BooleanField(
                        default=True,
                        help_text="If True, acceptance fee is deducted from first term tuition",
                    ),
                ),
                (
                    "max_applications",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of applications for this class (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission Fee Structure",
                "verbose_name_plural": "Admission Fee Structures",
                "ordering": ["admission_session"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: '2025/2026 New Students Admission'",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField(help_text="When applications open")),
                ("end_date", models.DateField(help_text="When applications close")),
                (
                    "require_acceptance_fee",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this session requires acceptance fees",
                    ),
                ),
                (
                    "acceptance_fee_deadline_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="Days after approval to pay acceptance fee and accept offer",
                    ),
                ),
                (
                    "application_number_prefix",
                    models.CharField(
                        default="ADM",
                        help_text="Prefix for application numbers (e.g., 'ADM' -> ADM/2025/001)",
                        max_length=10,
                    ),
                ),
                (
                    "allow_public_applications",
                    models.BooleanField(
                        default=True,
                        help_text="Allow external applications without login",
                    ),
                ),
                (
                    "send_confirmation_emails",
                    models.BooleanField(
                        default=True, help_text="Send email confirmations to applicants"
                    ),
                ),
                (
                    "application_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions shown to parents at the start of application",
                    ),
                ),
                (
                    "approval_message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message sent when application is approved",
                    ),
                ),
                (
                    "rejection_message_template",
                    models.TextField(
                        blank=True, help_text="Template for rejection messages"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one session should be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission Session",
                "verbose_name_plural": "Admission Sessions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AllocatedSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekly_periods",
                    models.IntegerField(help_text="Total number of periods per week."),
                ),
                (
                    "max_daily_periods",
                    models.IntegerField(
                        default=2,
                        help_text="Maximum number of periods allowed per day for this subject.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Mathematics', 'Communication Skills'",
                        max_length=255,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum score for this criterion",
                        max_digits=5,
                    ),
                ),
                (
                    "achieved_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Score achieved by student",
                        max_digits=5,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Weight/importance multiplier (default 1.0)",
                        max_digits=4,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Specific feedback for this criterion"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "verbose_name": "Assessment Criterion",
                "verbose_name_plural": "Assessment Criteria",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'JSS 1 Entrance Exam', 'Primary Interview'",
                        max_length=255,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("entrance_exam", "Entrance Examination"),
                            ("interview", "Interview"),
                            ("aptitude_test", "Aptitude Test"),
                            ("screening", "Screening Test"),
                            ("oral_test", "Oral Test"),
                            ("practical", "Practical Assessment"),
                            ("psychometric", "Psychometric Test"),
                            ("portfolio_review", "Portfolio Review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Default duration in minutes"
                    ),
                ),
                (
                    "default_max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Default maximum score",
                        max_digits=5,
                    ),
                ),
                (
                    "default_pass_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Default pass mark",
                        max_digits=5,
                    ),
                ),
                (
                    "default_instructions",
                    models.TextField(
                        blank=True, help_text="Default instructions for this assessment"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active templates are available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assessment Template",
                "verbose_name_plural": "Assessment Templates",
                "ordering": ["assessment_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTemplateCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Mathematics', 'Communication Skills'",
                        max_length=255,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum score for this criterion",
                        max_digits=5,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Weight/importance multiplier",
                        max_digits=4,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this criterion assesses"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "verbose_name": "Assessment Template Criterion",
                "verbose_name_plural": "Assessment Template Criteria",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="e.g. JSS 1 Gold", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("grade_level__sequence_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, default=40)),
                ("occupied_sits", models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClassYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Example 2020", max_length=100, unique=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, help_text="Example Class of 2020", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("occupied_beds", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DormitoryAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(auto_now_add=True)),
                ("date_till", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_code",
                    models.CharField(
                        choices=[
                            ("CRECHE", "Creche/Playgroup"),
                            ("PRE_NURSERY", "Pre-Nursery"),
                            ("NURSERY_1", "Nursery 1"),
                            ("NURSERY_2", "Nursery 2"),
                            ("BASIC_1", "Basic 1 (Primary 1)"),
                            ("BASIC_2", "Basic 2 (Primary 2)"),
                            ("BASIC_3", "Basic 3 (Primary 3)"),
                            ("BASIC_4", "Basic 4 (Primary 4)"),
                            ("BASIC_5", "Basic 5 (Primary 5)"),
                            ("BASIC_6", "Basic 6 (Primary 6)"),
                            ("JSS_1", "JSS 1 (Basic 7)"),
                            ("JSS_2", "JSS 2 (Basic 8)"),
                            ("JSS_3", "JSS 3 (Basic 9)"),
                            ("SS_1", "SS 1"),
                            ("SS_2", "SS 2"),
                            ("SS_3", "SS 3"),
                        ],
                        help_text="Internal code for data analysis. Cannot be changed.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("PRE_PRIMARY", "Pre-Primary Education"),
                            ("PRIMARY", "Primary Education"),
                            ("JSS", "Junior Secondary School"),
                            ("SSS", "Senior Secondary School"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_name",
                    models.CharField(
                        help_text="Standard Universal Name", max_length=100
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="School-specific name (e.g., 'Year 1' instead of 'Basic 1'). Admin editable.",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence_order",
                    models.PositiveIntegerField(
                        help_text="Order for promotion (1, 2, 3...)"
                    ),
                ),
                ("min_age", models.PositiveIntegerField(default=0)),
                ("max_age", models.PositiveIntegerField(default=0)),
                (
                    "graduation_note",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'Graduates receive FSLC' or 'Graduates take WAEC'",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Configuration",
                "ordering": ("sequence_order",),
            },
        ),
        migrations.CreateModel(
            name="MessageToParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Message to be shown to Parents."),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="MessageToTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Message to be shown to Teachers."),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Middle Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "parent_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Guardian", "Guardian"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Personal phone number", max_length=150, unique=True
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="Current occupation",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "monthly_income",
                    models.FloatField(
                        blank=True,
                        help_text="Parent's average monthly income",
                        null=True,
                    ),
                ),
                (
                    "single_parent",
                    models.BooleanField(
                        blank=True, default=False, help_text="Is he/she a single parent"
                    ),
                ),
                (
                    "alt_email",
                    models.EmailField(
                        blank=True,
                        help_text="Personal email",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, upload_to="Parent_images")),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["email", "first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotion_method",
                    models.CharField(
                        choices=[
                            ("annual_average", "Annual Average (Nigeria Standard)"),
                            ("gpa", "GPA (International)"),
                            ("cumulative", "Cumulative Average (All Years)"),
                        ],
                        default="annual_average",
                        help_text="Method used to calculate promotion eligibility",
                        max_length=20,
                    ),
                ),
                (
                    "min_average_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Minimum Annual Average (0-100%) required to promote.",
                        max_digits=5,
                    ),
                ),
                (
                    "must_pass_english",
                    models.BooleanField(
                        default=True, help_text="Student must pass English Language?"
                    ),
                ),
                (
                    "must_pass_math",
                    models.BooleanField(
                        default=True, help_text="Student must pass Mathematics?"
                    ),
                ),
                (
                    "min_subjects_passed",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum count of subjects the student must pass.",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated description of this rule",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promotion Rule",
                "ordering": ["from_grade__sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="ReasonLeft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, validators=[academic.validators.stream_validator]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Student's phone number for login/notifications",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "can_login",
                    models.BooleanField(
                        default=False,
                        help_text="Allow student to access student portal",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=150, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Middle Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Last Name"
                    ),
                ),
                ("graduation_date", models.DateField(blank=True, null=True)),
                ("date_dismissed", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Islam", "Islam"),
                            ("Christian", "Christian"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "parent_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("admission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "admission_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("image", models.ImageField(blank=True, upload_to="Student_images")),
                (
                    "cache_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the student is currently active.",
                    ),
                ),
                (
                    "preferred_stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("arts", "Arts"),
                        ],
                        help_text="Student/Parent preferred stream for SS1 (Science/Commercial/Arts)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "assigned_stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("arts", "Arts"),
                        ],
                        help_text="Admin-assigned stream for SS1+ (final decision)",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["admission_number", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this enrollment is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this enrollment (e.g., 'Repeated year', 'Transferred mid-year')",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Class Enrollment",
                "verbose_name_plural": "Student Class Enrollments",
                "ordering": ["-academic_year__start_date", "student__admission_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="students_files/%(student_id)s/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "png", "docx"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Promoted"),
                            ("REPEATED", "Repeated"),
                            ("DOUBLE_PROMOTION", "Double Promotion"),
                            ("PROMOTED_ON_TRIAL", "Promoted on Trial"),
                            ("GRADUATED", "Graduated"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PROMOTED",
                        max_length=20,
                    ),
                ),
                (
                    "annual_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The student's final average score used for this decision.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("promotion_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional remarks (e.g., 'Failed Math twice')",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Record",
                "ordering": ["-promotion_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentsMedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="students_medical_files"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentsPreviousAcademicHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "former_school",
                    models.CharField(help_text="Former school name", max_length=255),
                ),
                ("last_gpa", models.FloatField()),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Indicate student's academic performance according to your observation",
                        max_length=255,
                    ),
                ),
                (
                    "academic_record",
                    models.FileField(
                        blank=True, upload_to="students_former_academic_files"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "subject_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "is_selectable",
                    models.BooleanField(
                        default=False, help_text="Select if subject is optional"
                    ),
                ),
                (
                    "graded",
                    models.BooleanField(
                        default=True, help_text="Teachers can submit grades"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["subject_code"],
            },
        ),
        migrations.CreateModel(
            name="SubTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empId",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                (
                    "tin_number",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=3, null=True, unique=True),
                ),
                ("salary", models.IntegerField(blank=True, null=True)),
                (
                    "unpaid_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("alt_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Employee_images"
                    ),
                ),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("id", "user__first_name", "user__last_name"),
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
