# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionapplication",
            name="acceptance_fee_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acceptance_fees",
                to="finance.receipt",
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="application_fee_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_fees",
                to="finance.receipt",
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="exam_fee_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_fees",
                to="finance.receipt",
            ),
        ),
    ]
