# Generated by Django 5.2.11 on 2026-02-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Globally unique student identifier (e.g., STU-A7K9X2M4)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="teacher_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Globally unique teacher identifier (e.g., TCH-B3N8Y6P1)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
