# Generated by Django 5.2.11 on 2026-07-23 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_initial"),
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocatedsubject",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_subjects",
                to="administration.term",
            ),
        ),
    ]
