# Generated by Django 5.2.11 on 2026-03-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_student_student_id_teacher_teacher_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academic.teacher",
            ),
        ),
    ]
