# Generated by Django 5.2.11 on 2026-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_allocatedsubject_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocatedsubject",
            name="is_mandatory",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this subject is mandatory (core) or optional (elective) for the class.",
            ),
        ),
    ]
