# Generated by Django 5.1 on 2025-11-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='nssf_number',
        ),
    ]
