# Generated by Django 5.2.11 on 2026-06-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_allow_null_class_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="unpaid_salary",
        ),
    ]
