# Generated by Django 5.2.11 on 2026-08-19 15:51

from django.db import migrations, models


def create_school_section_table(apps, schema_editor):
    table_name = "academic_schoolsection"
    with schema_editor.connection.cursor() as cursor:
        existing_tables = schema_editor.connection.introspection.table_names(cursor)
    if table_name not in existing_tables:
        schema_editor.create_model(apps.get_model("academic", "SchoolSection"))


def drop_school_section_table(apps, schema_editor):
    table_name = "academic_schoolsection"
    with schema_editor.connection.cursor() as cursor:
        existing_tables = schema_editor.connection.introspection.table_names(cursor)
    if table_name in existing_tables:
        schema_editor.delete_model(apps.get_model("academic", "SchoolSection"))


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_allocatedsubject_is_mandatory"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_school_section_table,
                    reverse_code=drop_school_section_table,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SchoolSection",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "system_code",
                            models.CharField(
                                choices=[
                                    ("PRE_PRIMARY", "Pre-Primary Education"),
                                    ("PRIMARY", "Primary Education"),
                                    ("JSS", "Junior Secondary School"),
                                    ("SSS", "Senior Secondary School"),
                                ],
                                help_text="Internal code for data analysis. Cannot be changed.",
                                max_length=20,
                                unique=True,
                            ),
                        ),
                        (
                            "default_name",
                            models.CharField(
                                help_text="Standard Universal Name", max_length=100
                            ),
                        ),
                        (
                            "alias",
                            models.CharField(
                                blank=True,
                                help_text="School-specific name (e.g., 'Nursery' instead of 'Pre-Primary'). Admin editable.",
                                max_length=100,
                            ),
                        ),
                        (
                            "sequence_order",
                            models.PositiveIntegerField(
                                help_text="Order for display (1, 2, 3...)"
                            ),
                        ),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "School Section",
                        "ordering": ("sequence_order",),
                    },
                ),
            ],
        ),
    ]
