# Generated by Django 5.1 on 2025-12-04 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_teacher_nssf_number'),
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_method', models.CharField(choices=[('annual_average', 'Annual Average (Nigeria Standard)'), ('gpa', 'GPA (International)'), ('custom', 'Custom Formula')], default='annual_average', help_text='Method used to calculate promotion eligibility', max_length=20)),
                ('minimum_annual_average', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum annual average required (e.g., 50.00%)', max_digits=5)),
                ('use_weighted_terms', models.BooleanField(default=False, help_text='If True, Term 3 weighted more than Term 1/2')),
                ('term1_weight', models.DecimalField(decimal_places=2, default=0.3, help_text='Weight for Term 1 (default 30%)', max_digits=3)),
                ('term2_weight', models.DecimalField(decimal_places=2, default=0.3, help_text='Weight for Term 2 (default 30%)', max_digits=3)),
                ('term3_weight', models.DecimalField(decimal_places=2, default=0.4, help_text='Weight for Term 3 (default 40%)', max_digits=3)),
                ('require_english_pass', models.BooleanField(default=True, help_text='Student must pass English to be promoted')),
                ('require_mathematics_pass', models.BooleanField(default=True, help_text='Student must pass Mathematics to be promoted')),
                ('minimum_subject_pass_percentage', models.DecimalField(decimal_places=2, default=40.0, help_text="Minimum % to consider a subject 'passed'", max_digits=5)),
                ('minimum_passed_subjects', models.IntegerField(default=6, help_text='Minimum number of subjects student must pass')),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum attendance % required (e.g., 70.00)', max_digits=5)),
                ('minimum_gpa', models.DecimalField(blank=True, decimal_places=2, default=2.0, help_text='Minimum GPA required (for GPA method)', max_digits=3, null=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='If True, promotion requires manual admin approval')),
                ('is_active', models.BooleanField(default=True, help_text='Only active rules are applied during promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_class_level', models.ForeignKey(help_text='Class level students are promoted FROM', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_from', to='academic.classlevel')),
                ('to_class_level', models.ForeignKey(help_text='Class level students are promoted TO', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_to', to='academic.classlevel')),
            ],
            options={
                'verbose_name': 'Promotion Rule',
                'verbose_name_plural': 'Promotion Rules',
                'ordering': ['from_class_level__id'],
                'unique_together': {('from_class_level', 'to_class_level')},
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('repeated', 'Repeated'), ('conditional', 'Conditional Promotion'), ('graduated', 'Graduated')], default='promoted', max_length=20)),
                ('term1_average', models.DecimalField(blank=True, decimal_places=2, help_text='Average for Term 1', max_digits=5, null=True)),
                ('term2_average', models.DecimalField(blank=True, decimal_places=2, help_text='Average for Term 2', max_digits=5, null=True)),
                ('term3_average', models.DecimalField(blank=True, decimal_places=2, help_text='Average for Term 3', max_digits=5, null=True)),
                ('annual_average', models.DecimalField(blank=True, decimal_places=2, help_text='Overall annual average (Nigerian method)', max_digits=5, null=True)),
                ('final_gpa', models.DecimalField(blank=True, decimal_places=2, help_text="Student's final GPA (International method)", max_digits=3, null=True)),
                ('total_subjects', models.IntegerField(default=0, help_text='Total subjects taken')),
                ('subjects_passed', models.IntegerField(default=0, help_text='Number of subjects passed')),
                ('subjects_failed', models.IntegerField(default=0, help_text='Number of subjects failed')),
                ('english_passed', models.BooleanField(default=False, help_text='Whether English was passed')),
                ('mathematics_passed', models.BooleanField(default=False, help_text='Whether Mathematics was passed')),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Student's attendance % for the year", max_digits=5, null=True)),
                ('total_school_days', models.IntegerField(default=0, help_text='Total school days in the year')),
                ('days_present', models.IntegerField(default=0, help_text='Days student was present')),
                ('days_absent', models.IntegerField(default=0, help_text='Days student was absent')),
                ('class_position', models.IntegerField(blank=True, help_text="Student's final position in class", null=True)),
                ('total_students_in_class', models.IntegerField(blank=True, help_text='Total students in the class', null=True)),
                ('meets_criteria', models.BooleanField(default=True, help_text='Whether student met automatic promotion criteria')),
                ('reason', models.TextField(blank=True, help_text='Explanation for promotion decision (especially if repeated/overridden)')),
                ('promotion_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year this promotion occurred', on_delete=django.db.models.deletion.CASCADE, to='administration.academicyear')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotions', to=settings.AUTH_USER_MODEL)),
                ('from_class', models.ForeignKey(help_text='Classroom student was promoted FROM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='academic.classroom')),
                ('from_class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_level_promotions_from', to='academic.classlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='academic.student')),
                ('to_class', models.ForeignKey(blank=True, help_text='Classroom student was promoted TO (null if repeated/graduated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='academic.classroom')),
                ('to_class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_level_promotions_to', to='academic.classlevel')),
            ],
            options={
                'verbose_name': 'Student Promotion',
                'verbose_name_plural': 'Student Promotions',
                'ordering': ['-promotion_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'academic_year'], name='academic_st_student_37b1db_idx'), models.Index(fields=['status'], name='academic_st_status_2840c4_idx'), models.Index(fields=['academic_year'], name='academic_st_academi_87bf70_idx')],
            },
        ),
    ]
