# Generated by Django 5.2.11 on 2026-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_remove_teacher_salary_remove_teacher_unpaid_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
