# Generated by Django 5.1 on 2025-12-05 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_promotionrule_studentpromotion'),
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclassenrollment',
            options={'ordering': ['-academic_year__start_date', 'student__admission_number'], 'verbose_name': 'Student Class Enrollment', 'verbose_name_plural': 'Student Class Enrollments'},
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_stream',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('commercial', 'Commercial'), ('arts', 'Arts')], help_text='Admin-assigned stream for SS1+ (final decision)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='can_login',
            field=models.BooleanField(default=False, help_text='Allow student to access student portal'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's phone number for login/notifications", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_stream',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('commercial', 'Commercial'), ('arts', 'Arts')], help_text='Student/Parent preferred stream for SS1 (Science/Commercial/Arts)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Optional: Student's user account for portal access", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this enrollment is currently active'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='notes',
            field=models.TextField(blank=True, help_text="Additional notes about this enrollment (e.g., 'Repeated year', 'Transferred mid-year')"),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='administration.academicyear'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.classroom'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentclassenrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
