# Generated by Django 5.1 on 2025-12-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_studentclassenrollment_options_and_more'),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.academicyear'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='academic.classroom'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='academic.student'),
        ),
    ]
