# Generated by Django 5.2.11 on 2026-08-22 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_alter_subtopic_options_alter_topic_options_and_more"),
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclassenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_classes",
                to="academic.student",
            ),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="academic.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="topic",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="academic.subject",
            ),
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("NERDC", "NERDC"),
                            ("STATE", "State Ministry / Education Authority"),
                            ("SCHOOL", "School"),
                            ("OTHER", "Other"),
                        ],
                        default="NERDC",
                        max_length=20,
                    ),
                ),
                (
                    "authority_name",
                    models.CharField(
                        blank=True,
                        help_text="Issuing authority, e.g. Nigerian Educational Research and Development Council.",
                        max_length=200,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Curriculum edition/version if applicable.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-effective_from", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"),
                        name="unique_curriculum_name_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CurriculumSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academic.curriculum",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_subjects",
                        to="academic.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_subjects",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["grade_level__sequence_order", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Optional curriculum theme/strand under which the topic is organised.",
                        max_length=255,
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        blank=True,
                        help_text="Curriculum-specific content or scope for this topic.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_topics",
                        to="academic.curriculumsubject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_mappings",
                        to="academic.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "topic__name"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumGuidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_activities", models.TextField(blank=True)),
                ("learner_activities", models.TextField(blank=True)),
                ("teaching_learning_materials", models.TextField(blank=True)),
                ("evaluation_guide", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum_topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidance",
                        to="academic.curriculumtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_objectives",
                        to="academic.curriculumtopic",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_objectives",
                        to="academic.subtopic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_date", models.DateField()),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "previous_knowledge",
                    models.TextField(
                        blank=True,
                        help_text="Relevant knowledge learners are expected to already have.",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "lesson_content",
                    models.TextField(
                        blank=True, help_text="Main lesson notes/content."
                    ),
                ),
                ("teacher_activities", models.TextField(blank=True)),
                ("learner_activities", models.TextField(blank=True)),
                ("teaching_materials", models.TextField(blank=True)),
                (
                    "evaluation",
                    models.TextField(
                        blank=True,
                        help_text="Questions or activities used to assess understanding during/after the lesson.",
                    ),
                ),
                (
                    "assignment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Assignment or follow-up work planned for learners after the lesson.",
                    ),
                ),
                ("references", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_plans",
                        to="academic.allocatedsubject",
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lesson_plans",
                        to="academic.learningobjective",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_lesson_plans",
                        to="academic.teacher",
                    ),
                ),
                (
                    "subtopics",
                    models.ManyToManyField(
                        blank=True, related_name="lesson_plans", to="academic.subtopic"
                    ),
                ),
            ],
            options={
                "ordering": ["-lesson_date", "allocation__class_room"],
            },
        ),
        migrations.CreateModel(
            name="LessonDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("PARTIAL", "Partially Completed"),
                            ("NOT_TAUGHT", "Not Taught"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("taught_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "teacher_notes",
                    models.TextField(
                        blank=True,
                        help_text="Teacher's notes on how the lesson went, student understanding, challenges, etc.",
                    ),
                ),
                (
                    "learner_response",
                    models.TextField(
                        blank=True,
                        help_text="General observations about learner participation and understanding.",
                    ),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("next_lesson_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "objectives_covered",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lesson_deliveries",
                        to="academic.learningobjective",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_lesson_deliveries",
                        to="academic.teacher",
                    ),
                ),
                (
                    "subtopics_covered",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lesson_deliveries",
                        to="academic.subtopic",
                    ),
                ),
                (
                    "lesson_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="academic.lessonplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonPlanMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="lesson_plans/materials/%Y/%m/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academic.lessonplan",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SchemeOfWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes_of_work",
                        to="administration.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schemes_of_work",
                        to="academic.teacher",
                    ),
                ),
                (
                    "curriculum_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schemes_of_work",
                        to="academic.curriculumsubject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes_of_work",
                        to="administration.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemeOfWorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional school-specific lesson/scheme title.",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheme_items",
                        to="academic.curriculumtopic",
                    ),
                ),
                (
                    "learning_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheme_items",
                        to="academic.learningobjective",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="academic.schemeofwork",
                    ),
                ),
                (
                    "subtopics",
                    models.ManyToManyField(
                        blank=True, related_name="scheme_items", to="academic.subtopic"
                    ),
                ),
            ],
            options={
                "ordering": ["week_number", "order"],
            },
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="scheme_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_plans",
                to="academic.schemeofworkitem",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumsubject",
            index=models.Index(
                fields=["curriculum", "grade_level", "subject"],
                name="academic_cu_curricu_84065f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsubject",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "subject", "grade_level"),
                name="unique_curriculum_subject_grade",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumtopic",
            constraint=models.UniqueConstraint(
                fields=("curriculum_subject", "topic"),
                name="unique_topic_per_curriculum_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumtopic",
            constraint=models.UniqueConstraint(
                fields=("curriculum_subject", "order"),
                name="unique_curriculum_topic_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningobjective",
            constraint=models.UniqueConstraint(
                fields=("curriculum_topic", "order"),
                name="unique_learning_objective_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeofwork",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("academic_year", "term", "curriculum_subject"),
                name="unique_active_scheme_per_term_curriculum_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="schemeofworkitem",
            index=models.Index(
                fields=["scheme", "week_number"], name="academic_sc_scheme__380b60_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schemeofworkitem",
            constraint=models.UniqueConstraint(
                fields=("scheme", "week_number", "order"),
                name="unique_scheme_item_order_per_week",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonplan",
            index=models.Index(
                fields=["allocation", "lesson_date"],
                name="academic_le_allocat_c27bbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonplan",
            index=models.Index(fields=["status"], name="academic_le_status_51bb95_idx"),
        ),
    ]
