# Generated by Django 5.2.11 on 2026-08-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_alter_studentclassenrollment_student_and_more"),
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicApprovalPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow",
                    models.CharField(
                        choices=[
                            ("SCHEME_OF_WORK", "Scheme of Work"),
                            ("LESSON_PLAN", "Lesson Plan"),
                            ("QUESTION_BANK", "Question Bank"),
                            ("CBT_PUBLISH", "CBT Publish"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "approval_route",
                    models.CharField(
                        choices=[
                            ("ADMIN_ONLY", "Admin / Principal Only"),
                            (
                                "ACADEMIC_LEADER_OR_ADMIN",
                                "Academic Leader (HOD / Head Teacher) or Admin",
                            ),
                        ],
                        default="ADMIN_ONLY",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Academic Approval Policies",
                "ordering": ["workflow"],
            },
        ),
        migrations.AddField(
            model_name="schemeofwork",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schemeofwork",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schemeofwork",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_schemes_of_work",
                to="academic.teacher",
            ),
        ),
        migrations.AddField(
            model_name="schemeofwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schemeofwork",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AcademicLeadershipAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HOD", "Head of Department"),
                            ("HEAD_TEACHER", "Head Teacher"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRE_PRIMARY", "Pre-Primary Education"),
                            ("PRIMARY", "Primary Education"),
                            ("JSS", "Junior Secondary School"),
                            ("SSS", "Senior Secondary School"),
                        ],
                        help_text="Required if role is HEAD_TEACHER.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leadership_assignments",
                        to="administration.academicyear",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required if role is HOD.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leadership_assignments",
                        to="academic.department",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leadership_assignments",
                        to="academic.teacher",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-academic_year__start_date",
                    "role",
                    "department",
                    "section",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("role", "HOD")),
                        fields=("department", "academic_year"),
                        name="unique_active_hod_per_department_year",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("role", "HEAD_TEACHER")
                        ),
                        fields=("section", "academic_year"),
                        name="unique_active_head_teacher_per_section_year",
                    ),
                ],
            },
        ),
    ]
