# Generated by Django 5.1 on 2025-12-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_admissionapplication_admissionassessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='date_of_birth',
        ),
    ]
