# Generated by Django 5.2.11 on 2026-08-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_staff_identities(apps, schema_editor):
    Staff = apps.get_model('academic', 'Staff')
    Teacher = apps.get_model('academic', 'Teacher')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    for teacher in Teacher.objects.select_related('user').all().iterator():
        if not teacher.user_id:
            continue
        staff, _ = Staff.objects.get_or_create(
            user_id=teacher.user_id,
            defaults={
                'staff_id': teacher.teacher_id or f'STF-T-{teacher.pk}',
                'role': 'TEACHER',
                'designation': teacher.designation or 'Teacher',
                'image': teacher.image,
                'is_active': not teacher.inactive,
            },
        )
        if staff.role != 'TEACHER':
            staff.role = 'TEACHER'
            staff.save(update_fields=['role'])
        if teacher.staff_id != staff.pk:
            teacher.staff_id = staff.pk
            teacher.save(update_fields=['staff'])

    users = User.objects.filter(is_active=True).filter(
        models.Q(is_admin=True) | models.Q(is_accountant=True)
    )
    for user in users.iterator():
        if Staff.objects.filter(user_id=user.pk).exists():
            continue
        role = 'ADMINISTRATOR' if user.is_admin else 'ACCOUNTANT'
        Staff.objects.create(
            user_id=user.pk,
            staff_id=f'STF-U-{user.pk}',
            role=role,
            designation=role.title(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_academicapprovalpolicy_schemeofwork_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMINISTRATOR', 'Administrator'), ('ACCOUNTANT', 'Accountant'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Employee_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='academic.department')),
                ('user', models.OneToOneField(blank=True, help_text='Optional login account for this staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('staff_id',),
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff',
            field=models.OneToOneField(blank=True, help_text='General staff identity. Teacher.user remains authoritative during transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='academic.staff'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role', 'is_active'], name='academic_st_role_71b1e1_idx'),
        ),
        migrations.RunPython(backfill_staff_identities, migrations.RunPython.noop),
    ]
