# Generated by Django 5.1 on 2025-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_student_options_remove_teacher_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_vii_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
