# Generated by Django 5.1 on 2025-05-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_student_std_vii_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prem_number',
            new_name='prems_number',
        ),
    ]
