# Generated by Django 5.1 on 2025-12-29 - Step 1: Clean Duplicates

from django.db import migrations


def clean_duplicate_ids(apps, schema_editor):
    """
    Clean up duplicate national_id and tin_number values by setting duplicates to NULL.
    Keep the first occurrence and nullify the rest.
    Use raw SQL to avoid trigger issues.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Clean Teacher national_id duplicates
        cursor.execute("""
            WITH duplicates AS (
                SELECT id, national_id,
                       ROW_NUMBER() OVER (PARTITION BY national_id ORDER BY id) as row_num
                FROM academic_teacher
                WHERE national_id IS NOT NULL
            )
            UPDATE academic_teacher
            SET national_id = NULL
            WHERE id IN (
                SELECT id FROM duplicates WHERE row_num > 1
            )
        """)
        if cursor.rowcount > 0:
            print(f"Cleaned {cursor.rowcount} duplicate Teacher national_id values")

        # Clean Teacher tin_number duplicates
        cursor.execute("""
            WITH duplicates AS (
                SELECT id, tin_number,
                       ROW_NUMBER() OVER (PARTITION BY tin_number ORDER BY id) as row_num
                FROM academic_teacher
                WHERE tin_number IS NOT NULL
            )
            UPDATE academic_teacher
            SET tin_number = NULL
            WHERE id IN (
                SELECT id FROM duplicates WHERE row_num > 1
            )
        """)
        if cursor.rowcount > 0:
            print(f"Cleaned {cursor.rowcount} duplicate Teacher tin_number values")

        # Clean Parent national_id duplicates
        cursor.execute("""
            WITH duplicates AS (
                SELECT id, national_id,
                       ROW_NUMBER() OVER (PARTITION BY national_id ORDER BY id) as row_num
                FROM academic_parent
                WHERE national_id IS NOT NULL
            )
            UPDATE academic_parent
            SET national_id = NULL
            WHERE id IN (
                SELECT id FROM duplicates WHERE row_num > 1
            )
        """)
        if cursor.rowcount > 0:
            print(f"Cleaned {cursor.rowcount} duplicate Parent national_id values")


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_remove_parent_date_of_birth'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_ids, reverse_code=migrations.RunPython.noop),
    ]
