# Generated by Django 5.1 on 2025-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_clean_duplicate_ids_step1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tin_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
