# Generated by Django 5.1 on 2025-05-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_rename_prem_number_student_prems_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='academic.parent'),
        ),
    ]
