# Generated by Django 5.1 on 2026-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_parent_national_id_alter_teacher_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
