# Generated by Django 5.2.11 on 2026-08-23 09:35

import academic.models.numbering
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initialize_student_sequence_scopes(apps, schema_editor):
    Sequence = apps.get_model('academic', 'AdmissionNumberSequence')
    for sequence in Sequence.objects.all().iterator():
        sequence.reset_policy = 'academic_year'
        sequence.scope_key = str(sequence.year)
        sequence.save(update_fields=('reset_policy', 'scope_key'))


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_admissiondocument_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplicationNumberPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_width', models.PositiveSmallIntegerField(default=3)),
                ('reset_policy', models.CharField(choices=[('never', 'Never'), ('academic_year', 'Academic year')], default='academic_year', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(default='{PREFIX}/{YEAR}/{SEQ}', max_length=100, validators=[academic.models.numbering.validate_number_pattern])),
                ('prefix', models.CharField(default='ADM', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionApplicationNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_policy', models.CharField(choices=[('never', 'Never'), ('academic_year', 'Academic year')], max_length=20)),
                ('scope_key', models.CharField(max_length=40)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmissionNumberPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_width', models.PositiveSmallIntegerField(default=4)),
                ('reset_policy', models.CharField(choices=[('never', 'Never'), ('academic_year', 'Academic year')], default='academic_year', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(default='{PREFIX}-{YEAR}-{SEQ}', max_length=100, validators=[academic.models.numbering.validate_number_pattern])),
                ('prefix', models.CharField(default='ADM', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='admissionnumbersequence',
            name='reset_policy',
            field=models.CharField(default='academic_year', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionnumbersequence',
            name='scope_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='admissionnumbersequence',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            initialize_student_sequence_scopes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='admissionnumbersequence',
            constraint=models.UniqueConstraint(fields=('reset_policy', 'scope_key'), name='academic_unique_student_number_scope'),
        ),
        migrations.AddField(
            model_name='admissionapplicationnumberpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='admissionapplicationnumbersequence',
            constraint=models.UniqueConstraint(fields=('reset_policy', 'scope_key'), name='academic_unique_application_number_scope'),
        ),
        migrations.AddField(
            model_name='studentadmissionnumberpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='admissionapplicationnumberpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='academic_one_active_application_number_policy'),
        ),
        migrations.AddConstraint(
            model_name='studentadmissionnumberpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='academic_one_active_student_number_policy'),
        ),
    ]
