# Generated by Django 5.1 on 2025-06-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_student_parent_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='debt',
        ),
    ]
