# Generated by Django 5.2.11 on 2026-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_admissions_numbering_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(editable=False, help_text='Auto-generated (e.g., ADM/2025/001)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
