# Generated by Django 5.1 on 2025-07-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_student_debt'),
        ('administration', '0005_remove_academicyear_graduation_date'),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='StudentClassEnrollment',
        ),
    ]
