# Generated by Django 5.1 on 2026-01-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_classlevel_id_alter_gradelevel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='department',
            name='order_rank',
        ),
    ]
