# Generated by Django 5.1 on 2026-01-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionfeestructure',
            options={'ordering': ['admission_session'], 'verbose_name': 'Admission Fee Structure', 'verbose_name_plural': 'Admission Fee Structures'},
        ),
        migrations.AlterUniqueTogether(
            name='admissionfeestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='admissionfeestructure',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, help_text='Grade levels this fee applies to (e.g., JSS1, SS1)', related_name='admission_fee_structures', to='academic.gradelevel'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='applying_for_class',
            field=models.ForeignKey(help_text='Class student is applying for', on_delete=django.db.models.deletion.CASCADE, to='academic.gradelevel'),
        ),
        migrations.RemoveField(
            model_name='admissionfeestructure',
            name='class_room',
        ),
    ]
