# Generated by Django 5.1 on 2025-07-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_rename_studentclass_studentclassenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
