# Generated by Django 5.2.11 on 2026-08-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0016_remove_teacher_address_and_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradelevel",
            name="system_code",
            field=models.CharField(
                choices=[
                    ("CRECHE", "Creche/Playgroup"),
                    ("PRE_NURSERY", "Pre-Nursery"),
                    ("NURSERY_1", "Nursery 1"),
                    ("NURSERY_2", "Nursery 2"),
                    ("NURSERY_3", "Nursery 3"),
                    ("BASIC_1", "Basic 1 (Primary 1)"),
                    ("BASIC_2", "Basic 2 (Primary 2)"),
                    ("BASIC_3", "Basic 3 (Primary 3)"),
                    ("BASIC_4", "Basic 4 (Primary 4)"),
                    ("BASIC_5", "Basic 5 (Primary 5)"),
                    ("BASIC_6", "Basic 6 (Primary 6)"),
                    ("JSS_1", "JSS 1 (Basic 7)"),
                    ("JSS_2", "JSS 2 (Basic 8)"),
                    ("JSS_3", "JSS 3 (Basic 9)"),
                    ("SS_1", "SS 1"),
                    ("SS_2", "SS 2"),
                    ("SS_3", "SS 3"),
                ],
                help_text="Internal code for data analysis. Cannot be changed.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
