# Generated by Django 5.2.11 on 2026-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0018_classroom_grade_level_simplification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(
                help_text="Classroom name (e.g. 'Oleander', 'A', 'Gold')",
                max_length=150,
            ),
        ),
    ]
