# Generated by Django 5.2.11 on 2026-08-26 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0019_alter_classroom_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumtopic",
            name="source_page_end",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curriculumtopic",
            name="source_page_start",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="curriculumtopic",
            name="source_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learningobjective",
            name="source_page",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningobjective",
            name="source_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="CurriculumImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("source_checksum", models.CharField(blank=True, max_length=64)),
                ("grade_filter", models.CharField(blank=True, max_length=50)),
                ("subject_filter", models.CharField(blank=True, max_length=100)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured entity metric counts (CREATED, UPDATED, REUSED, UNCHANGED).",
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="academic.curriculum",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curriculum_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="curriculumtopic",
            name="last_import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculum_topics",
                to="academic.curriculumimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="learningobjective",
            name="last_import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_objectives",
                to="academic.curriculumimportbatch",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("authority", models.CharField(blank=True, max_length=200)),
                (
                    "publication_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("version", models.CharField(blank=True, max_length=100)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("DOCX", "Word Document"),
                            ("XLSX", "Excel Spreadsheet"),
                            ("MANUAL", "Manual Entry / Structured JSON"),
                            ("OTHER", "Other Source"),
                        ],
                        default="PDF",
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Official ISBN, Gazette number, or regulatory circular reference.",
                        max_length=255,
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Deterministic SHA-256 checksum of the original source document.",
                        max_length=64,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="curriculum_sources/%Y/%m/"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_curriculum_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="academic.curriculum",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "title"],
            },
        ),
        migrations.AddField(
            model_name="curriculumimportbatch",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_batches",
                to="academic.curriculumsource",
            ),
        ),
        migrations.AddField(
            model_name="curriculumtopic",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculum_topics",
                to="academic.curriculumsource",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checksum_sha256", ""), _negated=True),
                fields=("curriculum", "checksum_sha256"),
                name="unique_curriculum_source_checksum",
            ),
        ),
    ]
