# Generated by Django 5.2.11 on 2026-08-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_curriculumtopic_source_page_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Published Scheme of Work', max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_schemes', to='academic.curriculumsubject')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schemes', to='academic.curriculumsource')),
            ],
            options={
                'ordering': ['curriculum_subject', 'name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='PublishedSchemeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField()),
                ('week_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('INSTRUCTION', 'Instruction'), ('REVISION', 'Revision'), ('ASSESSMENT', 'Assessment'), ('EXAMINATION', 'Examination'), ('BREAK', 'Break'), ('PREPARATION', 'Preparation'), ('CLOSING', 'Closing'), ('OTHER', 'Other')], default='INSTRUCTION', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content_summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('teacher_activities', models.TextField(blank=True)),
                ('pupil_activities', models.TextField(blank=True)),
                ('learning_resources', models.TextField(blank=True)),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scheme_entries', to='academic.curriculumtopic')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scheme_entries', to='academic.curriculumimportbatch')),
                ('learning_objectives', models.ManyToManyField(blank=True, related_name='published_scheme_entries', to='academic.learningobjective')),
                ('published_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academic.publishedscheme')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scheme_entries', to='academic.curriculumsource')),
                ('subtopics', models.ManyToManyField(blank=True, related_name='published_scheme_entries', to='academic.subtopic')),
            ],
            options={
                'ordering': ['term_number', 'order', 'week_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('PRESCRIBED_TEXT', 'Prescribed Text'), ('RECOMMENDED_TEXT', 'Recommended Text'), ('REFERENCE', 'Reference'), ('INSTRUCTIONAL_NOTE', 'Instructional Note'), ('EVALUATION', 'Evaluation'), ('ASSIGNMENT', 'Assignment'), ('PRACTICAL', 'Practical'), ('EXAMPLE', 'Example'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=1)),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.curriculumsubject')),
                ('curriculum_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.curriculumtopic')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_resources', to='academic.curriculumimportbatch')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_resources', to='academic.curriculumsource')),
                ('published_scheme_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.publishedschemeentry')),
            ],
            options={
                'ordering': ['curriculum_subject', 'order', 'title', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='publishedscheme',
            constraint=models.UniqueConstraint(fields=('curriculum_subject', 'name', 'version'), name='unique_published_scheme_version'),
        ),
        migrations.AddIndex(
            model_name='publishedschemeentry',
            index=models.Index(fields=['published_scheme', 'term_number', 'week_start'], name='academic_pu_publish_d73214_idx'),
        ),
        migrations.AddConstraint(
            model_name='publishedschemeentry',
            constraint=models.UniqueConstraint(fields=('published_scheme', 'term_number', 'order'), name='unique_published_scheme_term_order'),
        ),
        migrations.AddIndex(
            model_name='curriculumresource',
            index=models.Index(fields=['curriculum_subject', 'resource_type', 'is_active'], name='academic_cu_curricu_f1c8b4_idx'),
        ),
    ]
