# Generated by Django 5.2.11 on 2026-08-29 09:58

import academic.models.numbering
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0021_publishedscheme_publishedschemeentry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_type",
                    models.CharField(
                        choices=[
                            ("student_admission", "Student admission number"),
                            ("admission_application", "Admission application number"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reset_policy",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("academic_year", "Academic year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_key", models.CharField(max_length=100)),
                ("last_value", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AdmissionApplicationNumberSequence",
        ),
        migrations.AddField(
            model_name="schoolsection",
            name="number_code",
            field=models.CharField(
                blank=True,
                help_text="Optional short representation used in generated numbers, e.g. PN, JS, SS.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplicationnumberpolicy",
            name="pattern",
            field=models.CharField(
                default="{PREFIX}/{YYYY}/{SEQ}",
                max_length=100,
                validators=[academic.models.numbering.validate_number_pattern],
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplicationnumberpolicy",
            name="prefix",
            field=models.CharField(default="APP", max_length=30),
        ),
        migrations.AlterField(
            model_name="studentadmissionnumberpolicy",
            name="pattern",
            field=models.CharField(
                default="{PREFIX}/{YYYY}/{SEQ}",
                max_length=100,
                validators=[academic.models.numbering.validate_number_pattern],
            ),
        ),
        migrations.AddConstraint(
            model_name="numbersequence",
            constraint=models.UniqueConstraint(
                fields=("sequence_type", "reset_policy", "scope_key"),
                name="academic_unique_number_sequence_scope",
            ),
        ),
    ]
