# Generated by Django 5.2.11 on 2026-08-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0024_scheme_work_actor_and_responsible_teacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdmissionNumberSequence",
        ),
    ]
