# Generated by Django 5.1.4 on 2026-08-30
from django.db import migrations, models
import django.db.models.deletion


def backfill_canonical_identities(apps, schema_editor):
    CurriculumSubject = apps.get_model("academic", "CurriculumSubject")
    CurriculumTopic = apps.get_model("academic", "CurriculumTopic")
    SubTopic = apps.get_model("academic", "SubTopic")
    LearningObjective = apps.get_model("academic", "LearningObjective")
    PublishedSchemeEntry = apps.get_model("academic", "PublishedSchemeEntry")

    # 1. Backfill CurriculumSubject name and code
    for cs in CurriculumSubject.objects.select_related("subject").all():
        if cs.subject:
            cs.name = cs.subject.name
            cs.code = cs.subject.subject_code or ""
        else:
            cs.name = f"Curriculum Subject {cs.id}"
            cs.code = ""
        cs.save(update_fields=["name", "code"])

    # 2. Backfill CurriculumTopic name
    for ct in CurriculumTopic.objects.select_related("topic").all():
        if ct.topic:
            ct.name = ct.topic.name
        else:
            ct.name = f"Curriculum Topic {ct.id}"
        ct.save(update_fields=["name"])

    # 3. Backfill CurriculumTopic.subtopics M2M relationship
    for ct in CurriculumTopic.objects.all():
        subtopic_ids = set()
        if ct.topic_id:
            subtopic_ids.update(
                SubTopic.objects.filter(topic_id=ct.topic_id).values_list("id", flat=True)
            )
        # Objectives attached to this curriculum topic
        subtopic_ids.update(
            LearningObjective.objects.filter(
                curriculum_topic_id=ct.id, subtopic__isnull=False
            ).values_list("subtopic_id", flat=True)
        )
        # Published scheme entries attached to this curriculum topic
        for pse in PublishedSchemeEntry.objects.filter(curriculum_topic_id=ct.id):
            subtopic_ids.update(pse.subtopics.values_list("id", flat=True))

        if subtopic_ids:
            ct.subtopics.add(*subtopic_ids)


def reverse_backfill_canonical_identities(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0025_delete_admissionnumbersequence"),
    ]

    operations = [
        # ── Step 1: Add new canonical fields as nullable ──
        migrations.AddField(
            model_name="curriculumsubject",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="curriculumsubject",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="curriculumtopic",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="curriculumtopic",
            name="subtopics",
            field=models.ManyToManyField(
                blank=True,
                related_name="curriculum_topics",
                to="academic.subtopic",
            ),
        ),

        # ── Step 2: Data Backfill ──
        migrations.RunPython(
            code=backfill_canonical_identities,
            reverse_code=reverse_backfill_canonical_identities,
        ),

        # ── Step 3: Enforce NOT NULL on canonical names ──
        migrations.AlterField(
            model_name="curriculumsubject",
            name="name",
            field=models.CharField(max_length=200, null=False),
        ),
        migrations.AlterField(
            model_name="curriculumtopic",
            name="name",
            field=models.CharField(max_length=255, null=False),
        ),

        # ── Step 4: Relax operational ForeignKeys to SET_NULL ──
        migrations.AlterField(
            model_name="curriculumsubject",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculum_subjects",
                to="academic.subject",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumtopic",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculum_mappings",
                to="academic.topic",
            ),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtopics",
                to="academic.topic",
            ),
        ),
        migrations.AlterField(
            model_name="learningobjective",
            name="subtopic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_objectives",
                to="academic.subtopic",
            ),
        ),

        # ── Step 5: Replace constraints and indexes ──
        migrations.AlterModelOptions(
            name="curriculumsubject",
            options={"ordering": ["grade_level__sequence_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="curriculumtopic",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="subtopic",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="curriculumsubject",
            name="unique_curriculum_subject_grade",
        ),
        migrations.AddConstraint(
            model_name="curriculumsubject",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "name", "grade_level"),
                name="unique_curriculum_subject_name_grade",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="curriculumtopic",
            name="unique_topic_per_curriculum_subject",
        ),
        migrations.AddConstraint(
            model_name="curriculumtopic",
            constraint=models.UniqueConstraint(
                fields=("curriculum_subject", "name"),
                name="unique_topic_name_per_curriculum_subject",
            ),
        ),
        migrations.RemoveIndex(
            model_name="curriculumsubject",
            name="academic_cu_curricu_84065f_idx",
        ),
        migrations.AddIndex(
            model_name="curriculumsubject",
            index=models.Index(
                fields=["curriculum", "grade_level", "name"],
                name="academic_cu_curricu_3385a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumsubject",
            index=models.Index(
                fields=["subject"],
                name="academic_cu_subject_e581d8_idx",
            ),
        ),
    ]
