# Generated by Django 5.2.11 on 2026-08-31 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_lessonplanmaterial_curriculum_provenance'),
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='The academic year during which this curriculum assignment is in effect.', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_assignments', to='administration.academicyear')),
                ('classroom', models.ForeignKey(blank=True, help_text='Applies specifically to this classroom.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_assignments', to='academic.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculum_assignments', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(help_text='The canonical curriculum framework applied.', on_delete=django.db.models.deletion.PROTECT, related_name='school_assignments', to='academic.curriculum')),
                ('grade_level', models.ForeignKey(blank=True, help_text='Applies to all classrooms in this grade unless overridden at classroom level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_assignments', to='academic.gradelevel')),
                ('section', models.ForeignKey(blank=True, help_text='Applies to all grades in this section unless overridden at grade or classroom level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_assignments', to='academic.schoolsection')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'section__sequence_order', 'grade_level__sequence_order'],
                'indexes': [models.Index(fields=['academic_year', 'is_active'], name='academic_cu_academi_c01586_idx'), models.Index(fields=['grade_level', 'academic_year'], name='academic_cu_grade_l_5bbeeb_idx'), models.Index(fields=['classroom', 'academic_year'], name='academic_cu_classro_266284_idx'), models.Index(fields=['section', 'academic_year'], name='academic_cu_section_be81be_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('section__isnull', False), ('grade_level__isnull', True), ('classroom__isnull', True)), models.Q(('section__isnull', True), ('grade_level__isnull', False), ('classroom__isnull', True)), models.Q(('section__isnull', True), ('grade_level__isnull', True), ('classroom__isnull', False)), models.Q(('section__isnull', True), ('grade_level__isnull', True), ('classroom__isnull', True)), _connector='OR'), name='curr_assign_single_scope_check'), models.UniqueConstraint(condition=models.Q(('classroom__isnull', True), ('grade_level__isnull', True), ('is_active', True), ('section__isnull', True)), fields=('academic_year',), name='unique_active_school_curr_assign'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('section__isnull', False)), fields=('academic_year', 'section'), name='unique_active_sec_curr_assign'), models.UniqueConstraint(condition=models.Q(('grade_level__isnull', False), ('is_active', True)), fields=('academic_year', 'grade_level'), name='unique_active_grade_curr_assign'), models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('is_active', True)), fields=('academic_year', 'classroom'), name='unique_active_cls_curr_assign')],
            },
        ),
    ]
