# Generated by Django 5.2.11 on 2026-09-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0028_curriculumassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="alt_phone",
            field=models.CharField(
                blank=True,
                help_text="Alternate phone number",
                max_length=150,
                null=True,
            ),
        ),
    ]
