# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        help_text="Day of the week",
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Start time of the class")),
                ("end_time", models.TimeField(help_text="End time of the class")),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Physical room where class takes place",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this period is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this period",
                        null=True,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Classroom this period is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="academic.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject being taught",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="academic.allocatedsubject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher assigned to teach this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periods",
                        to="academic.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["classroom", "day_of_week", "start_time"],
                        name="schedule_pe_classro_f65330_idx",
                    ),
                    models.Index(
                        fields=["teacher", "day_of_week", "start_time"],
                        name="schedule_pe_teacher_d0de02_idx",
                    ),
                ],
                "unique_together": {("day_of_week", "start_time", "classroom")},
            },
        ),
    ]
