# Generated by Django 5.1 on 2025-11-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_student_is_active'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this period is currently active'),
        ),
        migrations.AddField(
            model_name='period',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this period', null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='room_number',
            field=models.CharField(blank=True, help_text='Physical room where class takes place', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='classroom',
            field=models.ForeignKey(help_text='Classroom this period is for', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academic.classroom'),
        ),
        migrations.AlterField(
            model_name='period',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week', max_length=10),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(help_text='End time of the class'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(help_text='Start time of the class'),
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academic.allocatedsubject'),
        ),
        migrations.AlterField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher assigned to teach this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='academic.teacher'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['classroom', 'day_of_week', 'start_time'], name='schedule_pe_classro_f65330_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['teacher', 'day_of_week', 'start_time'], name='schedule_pe_teacher_d0de02_idx'),
        ),
    ]
