# Generated by Django 5.2.11 on 2026-07-23 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_allocatedsubject_term"),
        ("administration", "0002_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PeriodSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(
                        help_text="Ordinal position in the day, e.g. 1, 2, 3. Breaks get a number too so ordering stays correct."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional display label, e.g. 'Period 1' or 'Break'. Defaults to period_number if blank.",
                        max_length=50,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "is_break",
                    models.BooleanField(
                        default=False,
                        help_text="Break periods are excluded from subject/teacher assignment.",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_slots",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["term", "day_of_week", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="schedule.periodslot",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="academic.teacher",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="administration.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic.classroom",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="schedule.room",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="schedule.periodslot",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="academic.allocatedsubject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="academic.teacher",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="administration.term",
                    ),
                ),
            ],
            options={
                "ordering": ["slot__day_of_week", "slot__period_number"],
            },
        ),
        migrations.DeleteModel(
            name="Period",
        ),
        migrations.AddIndex(
            model_name="periodslot",
            index=models.Index(
                fields=["term", "day_of_week"], name="schedule_pe_term_id_69f808_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodslot",
            unique_together={("term", "day_of_week", "period_number")},
        ),
        migrations.AddIndex(
            model_name="teacheravailability",
            index=models.Index(
                fields=["teacher", "term"], name="schedule_te_teacher_57859a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacheravailability",
            unique_together={("teacher", "slot")},
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["classroom", "term"], name="schedule_ti_classro_d1eb10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["teacher", "term"], name="schedule_ti_teacher_cbb9a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["room", "term"], name="schedule_ti_room_id_661dc7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={("term", "slot", "classroom")},
        ),
    ]
