# Generated by Django 5.2.11 on 2026-07-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_allocatedsubject_term"),
        (
            "schedule",
            "0002_room_periodslot_teacheravailability_timetableentry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="activity_label",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Assembly', 'Extra-Moral Lesson', 'Library Period'. Used when subject is blank and this isn't a free period.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="is_free_period",
            field=models.BooleanField(
                default=False,
                help_text="Explicitly marks this slot as free for this classroom.",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for free periods or non-subject activities.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timetable_entries",
                to="academic.allocatedsubject",
            ),
        ),
    ]
