# Generated by Django 5.2.11 on 2026-07-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_allocatedsubject_is_mandatory"),
        ("schedule", "0003_timetableentry_activity_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodslot",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timetable_entries",
                to="schedule.periodslot",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for free periods or non-subject activities.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academic.allocatedsubject",
            ),
        ),
    ]
