# Generated by Django 5.2.11 on 2026-08-22 02:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0008_alter_studentclassenrollment_student_and_more"),
        ("examination", "0021_stage10_source_reference_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="FillBlankDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MatchingDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shuffle_right_items", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=1)),
                ("feedback", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CBTExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("instructions", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("shuffle_questions", models.BooleanField(default=False)),
                ("shuffle_options", models.BooleanField(default=False)),
                ("allow_back_navigation", models.BooleanField(default=True)),
                ("auto_submit", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="academic.classroom",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="examination.assessmentcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cbt_exams",
                        to="academic.teacher",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="examination.assessmentsession",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cbt_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="cbt.cbtexam",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_attempts",
                        to="academic.studentclassenrollment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_attempts",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AttemptGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("NEEDS_MANUAL", "Needs Manual Grading"),
                            ("GRADED", "Graded"),
                            ("POSTED", "Posted to Results"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "raw_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "normalized_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final CBT score normalized to the AssessmentComponent max_score.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="cbt.examattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cbt_exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint",
                        to="cbt.cbtexam",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlueprintRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE_CHOICE", "Single Choice"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("TRUE_FALSE", "True / False"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("NUMERIC", "Numeric"),
                            ("FILL_BLANK", "Fill in the Blank"),
                            ("ESSAY", "Essay / Theory"),
                            ("MATCHING", "Matching"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_count", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_rules",
                        to="academic.learningobjective",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_rules",
                        to="academic.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_rules",
                        to="academic.topic",
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="cbt.examblueprint",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blueprint_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_questions",
                        to="cbt.blueprintrule",
                    ),
                ),
                (
                    "cbt_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="cbt.cbtexam",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AttemptQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField()),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Student marked this question for review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_questions",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "exam_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_questions",
                        to="cbt.examquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="FillBlankItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blanks",
                        to="cbt.fillblankdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="FillBlankAcceptedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=500)),
                (
                    "blank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_answers",
                        to="cbt.fillblankitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_text", models.TextField()),
                ("right_text", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="cbt.matchingdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_banks",
                        to="academic.teacher",
                    ),
                ),
                (
                    "grade_levels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="question_banks",
                        to="academic.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Single Choice"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("TRUE_FALSE", "True / False"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("NUMERIC", "Numeric"),
                            ("FILL_BLANK", "Fill in the Blank"),
                            ("ESSAY", "Essay / Theory"),
                            ("MATCHING", "Matching"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "default_marks",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to="academic.teacher",
                    ),
                ),
                (
                    "grade_levels",
                    models.ManyToManyField(
                        related_name="cbt_questions", to="academic.gradelevel"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbt_questions",
                        to="academic.subject",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="academic.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="academic.topic",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="cbt.questionbank",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name", "topic__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="AttemptQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField()),
                (
                    "attempt_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_order",
                        to="cbt.attemptquestion",
                    ),
                ),
                (
                    "question_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_presentations",
                        to="cbt.questionoption",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Single Choice"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("TRUE_FALSE", "True / False"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("NUMERIC", "Numeric"),
                            ("FILL_BLANK", "Fill in the Blank"),
                            ("ESSAY", "Essay / Theory"),
                            ("MATCHING", "Matching"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "default_marks",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("text", models.TextField()),
                ("instructions", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_versions",
                        to="academic.teacher",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cbt.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "-version"],
            },
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_reviews",
                        to="academic.teacher",
                    ),
                ),
                (
                    "question_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cbt.questionversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="cbt.questionversion",
            ),
        ),
        migrations.CreateModel(
            name="QuestionLearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning_objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_alignments",
                        to="academic.learningobjective",
                    ),
                ),
                (
                    "question_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective_alignments",
                        to="cbt.questionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="cbt/question_attachments/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cbt.questionversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cbt.questionversion",
            ),
        ),
        migrations.CreateModel(
            name="NumericAnswerDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "tolerance",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Accepted absolute deviation from the expected value.",
                        max_digits=18,
                    ),
                ),
                (
                    "question_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_answer_definition",
                        to="cbt.questionversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matchingdefinition",
            name="question_version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matching_definition",
                to="cbt.questionversion",
            ),
        ),
        migrations.AddField(
            model_name="fillblankdefinition",
            name="question_version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fill_blank_definition",
                to="cbt.questionversion",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="question_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exam_questions",
                to="cbt.questionversion",
            ),
        ),
        migrations.CreateModel(
            name="EssayDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marking_guide", models.TextField(blank=True)),
                (
                    "model_answer",
                    models.TextField(
                        blank=True,
                        help_text="Optional reference answer for markers. Not auto-scored.",
                    ),
                ),
                ("minimum_words", models.PositiveIntegerField(blank=True, null=True)),
                ("maximum_words", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "question_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_definition",
                        to="cbt.questionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortAnswerDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
                ("trim_whitespace", models.BooleanField(default=True)),
                (
                    "question_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_answer_definition",
                        to="cbt.questionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortAnswerVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=500)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_answers",
                        to="cbt.shortanswerdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="cbt.attemptquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_selections",
                        to="cbt.questionoption",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="cbt.studentanswer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentFillBlankAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=500)),
                (
                    "blank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_answers",
                        to="cbt.fillblankitem",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blank_responses",
                        to="cbt.studentanswer",
                    ),
                ),
            ],
            options={
                "ordering": ["blank__position"],
            },
        ),
        migrations.CreateModel(
            name="StudentMatchingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "left_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cbt.matchingpair",
                    ),
                ),
                (
                    "selected_right_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cbt.matchingpair",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_responses",
                        to="cbt.studentanswer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentNumericAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "student_answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_response",
                        to="cbt.studentanswer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTextAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "student_answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_response",
                        to="cbt.studentanswer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttemptQuestionGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="True/False for objectively graded questions. May be null for manually graded questions.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AUTO_GRADED", "Auto Graded"),
                            ("PENDING_MANUAL", "Pending Manual Grading"),
                            ("MANUALLY_GRADED", "Manually Graded"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "grading_method",
                    models.CharField(
                        choices=[("AUTO", "Automatic"), ("MANUAL", "Manual")],
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="cbt.attemptquestion",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cbt_question_grades",
                        to="academic.teacher",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "grading_method"],
                        name="cbt_attempt_status_9b8072_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cbtexam",
            index=models.Index(
                fields=["session", "classroom", "subject"],
                name="cbt_cbtexam_session_83a40f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cbtexam",
            index=models.Index(fields=["status"], name="cbt_cbtexam_status_e8d2a0_idx"),
        ),
        migrations.AddConstraint(
            model_name="cbtexam",
            constraint=models.UniqueConstraint(
                fields=("session", "subject", "classroom", "component"),
                name="unique_cbt_exam_per_session_subject_class_component",
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["cbt_exam", "student"], name="cbt_examatt_cbt_exa_b60c8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["cbt_exam", "status"], name="cbt_examatt_cbt_exa_2918ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student", "status"], name="cbt_examatt_student_16e39e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                fields=("cbt_exam", "student"),
                name="unique_student_attempt_per_cbt_exam",
            ),
        ),
        migrations.AddIndex(
            model_name="blueprintrule",
            index=models.Index(
                fields=["blueprint", "topic", "subtopic"],
                name="cbt_bluepri_bluepri_cb4974_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blueprintrule",
            index=models.Index(
                fields=["question_type", "difficulty"],
                name="cbt_bluepri_questio_2c57ed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintrule",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "order"), name="unique_blueprint_rule_order"
            ),
        ),
        migrations.AddIndex(
            model_name="attemptquestion",
            index=models.Index(
                fields=["attempt", "display_order"],
                name="cbt_attempt_attempt_09a56b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestion",
            constraint=models.UniqueConstraint(
                fields=("attempt", "exam_question"),
                name="unique_exam_question_per_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestion",
            constraint=models.UniqueConstraint(
                fields=("attempt", "display_order"),
                name="unique_attempt_question_display_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="fillblankitem",
            constraint=models.UniqueConstraint(
                fields=("definition", "position"), name="unique_blank_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="fillblankacceptedanswer",
            constraint=models.UniqueConstraint(
                fields=("blank", "answer"), name="unique_fill_blank_answer"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchingpair",
            constraint=models.UniqueConstraint(
                fields=("definition", "order"), name="unique_matching_pair_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbank",
            constraint=models.UniqueConstraint(
                fields=("subject", "name"), name="unique_question_bank_per_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestionoption",
            constraint=models.UniqueConstraint(
                fields=("attempt_question", "question_option"),
                name="unique_option_per_attempt_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestionoption",
            constraint=models.UniqueConstraint(
                fields=("attempt_question", "display_order"),
                name="unique_attempt_option_display_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionversion",
            constraint=models.UniqueConstraint(
                fields=("question", "version"), name="unique_question_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question_version", "order"),
                name="unique_option_order_per_question_version",
            ),
        ),
        migrations.AddIndex(
            model_name="questionlearningobjective",
            index=models.Index(
                fields=["learning_objective", "question_version"],
                name="cbt_questio_learnin_a8cc1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionlearningobjective",
            constraint=models.UniqueConstraint(
                fields=("question_version", "learning_objective"),
                name="unique_question_version_learning_objective",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionlearningobjective",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("question_version",),
                name="unique_primary_objective_per_question_version",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "status"], name="cbt_questio_subject_d3fd69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type", "difficulty"],
                name="cbt_questio_questio_c09716_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(
                fields=["cbt_exam", "order"], name="cbt_examque_cbt_exa_531cc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(
                fields=["cbt_exam", "blueprint_rule"],
                name="cbt_examque_cbt_exa_2e7ba1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="examquestion",
            constraint=models.UniqueConstraint(
                fields=("cbt_exam", "order"), name="unique_exam_question_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="examquestion",
            constraint=models.UniqueConstraint(
                fields=("cbt_exam", "question_version"),
                name="unique_question_version_per_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="shortanswervariant",
            constraint=models.UniqueConstraint(
                fields=("definition", "answer"), name="unique_short_answer_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["is_answered"], name="cbt_student_is_answ_09bedc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentchoiceanswer",
            constraint=models.UniqueConstraint(
                fields=("student_answer", "question_option"),
                name="unique_selected_option_per_student_answer",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfillblankanswer",
            constraint=models.UniqueConstraint(
                fields=("student_answer", "blank"),
                name="unique_student_answer_per_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmatchinganswer",
            constraint=models.UniqueConstraint(
                fields=("student_answer", "left_pair"),
                name="unique_match_per_left_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmatchinganswer",
            constraint=models.UniqueConstraint(
                fields=("student_answer", "selected_right_pair"),
                name="unique_right_match_per_student_answer",
            ),
        ),
    ]
