# Generated by Django 5.2.11 on 2026-08-31 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


def materialize_existing_matching_items(apps, schema_editor):
    AttemptQuestion = apps.get_model('cbt', 'AttemptQuestion')
    AttemptMatchingItem = apps.get_model('cbt', 'AttemptMatchingItem')
    for attempt_question in AttemptQuestion.objects.filter(
        exam_question__question_version__question_type='MATCHING'
    ).iterator():
        pairs = list(
            attempt_question.exam_question.question_version
            .matching_definition.pairs.all().order_by('order')
        )
        right_pairs = sorted(
            pairs,
            key=lambda pair: (pair.right_text.casefold(), pair.pk),
        )
        AttemptMatchingItem.objects.bulk_create(
            [
                AttemptMatchingItem(
                    attempt_question=attempt_question,
                    matching_pair=pair,
                    side='LEFT',
                    display_order=order,
                )
                for order, pair in enumerate(pairs, start=1)
            ] + [
                AttemptMatchingItem(
                    attempt_question=attempt_question,
                    matching_pair=pair,
                    side='RIGHT',
                    display_order=order,
                )
                for order, pair in enumerate(right_pairs, start=1)
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptgrade',
            name='grading_error',
            field=models.TextField(blank=True, help_text='Internal grading failure detail; never exposed to students.'),
        ),
        migrations.AlterField(
            model_name='attemptgrade',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Grading Failed'), ('NEEDS_MANUAL', 'Needs Manual Grading'), ('GRADED', 'Graded'), ('POSTED', 'Posted to Results')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='AttemptMatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_order', models.PositiveIntegerField()),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_item_order', to='cbt.attemptquestion')),
                ('matching_pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_presentations', to='cbt.matchingpair')),
            ],
            options={
                'ordering': ['side', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('attempt_question', 'matching_pair', 'side'), name='unique_matching_item_side_per_attempt_question'), models.UniqueConstraint(fields=('attempt_question', 'side', 'display_order'), name='unique_matching_item_order_per_side')],
            },
        ),
        migrations.RunPython(
            materialize_existing_matching_items,
            migrations.RunPython.noop,
        ),
    ]
