# Generated by Django 5.2.11 on 2026-08-31 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    ExamAttempt = apps.get_model('cbt', 'ExamAttempt')
    AttemptQuestion = apps.get_model('cbt', 'AttemptQuestion')
    for attempt in ExamAttempt.objects.filter(public_id__isnull=True).iterator():
        attempt.public_id = uuid.uuid4()
        attempt.save(update_fields=['public_id'])
    for question in AttemptQuestion.objects.filter(public_id__isnull=True).iterator():
        question.public_id = uuid.uuid4()
        question.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_attemptgrade_grading_error_alter_attemptgrade_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attemptquestion',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='submission_snapshot_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='submitted_revision',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttemptAnswerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4)),
                ('client_id', models.UUIDField()),
                ('client_sequence', models.PositiveBigIntegerField()),
                ('base_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('SET', 'Set'), ('CLEAR', 'Clear')], max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('STALE', 'Stale')], max_length=12)),
                ('server_revision', models.PositiveBigIntegerField()),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_events', to='cbt.examattempt')),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_events', to='cbt.attemptquestion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['attempt', 'server_revision'], name='cbt_attempt_attempt_dc4e54_idx'), models.Index(fields=['attempt_question', 'client_id', 'client_sequence'], name='cbt_attempt_attempt_7be5dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'event_id'), name='unique_answer_event_per_attempt'), models.UniqueConstraint(fields=('attempt_question', 'client_id', 'client_sequence'), name='unique_client_sequence_per_attempt_question')],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestionClientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('last_client_sequence', models.PositiveBigIntegerField(default=0)),
                ('last_server_revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_states', to='cbt.attemptquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt_question', 'client_id'), name='unique_client_state_per_attempt_question')],
            },
        ),
    ]
