# Generated by Django 5.2.11 on 2026-09-01 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_curriculumassignment'),
        ('cbt', '0004_published_exam_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='attempt_expiry_policy',
            field=models.CharField(choices=[('CAP_AT_EXAM_CLOSE', 'Cap at exam close'), ('DURATION_ONLY', 'Duration only')], default='CAP_AT_EXAM_CLOSE', max_length=24),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttemptGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=12)),
                ('issuance_source', models.CharField(choices=[('ONLINE_START', 'Online start'), ('OFFLINE_PREPARATION', 'Offline preparation')], default='ONLINE_START', max_length=24)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_grants', to='cbt.cbtexam')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_cbt_attempt_grants', to='academic.teacher')),
                ('published_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_grants', to='cbt.publishedexamrevision')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_cbt_attempt_grants', to='academic.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_attempt_grants', to='academic.student')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='examattempt',
            name='attempt_grant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='cbt.attemptgrant'),
        ),
        migrations.AddIndex(
            model_name='attemptgrant',
            index=models.Index(fields=['student', 'exam', 'status'], name='cbt_attempt_student_bd3bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptgrant',
            index=models.Index(fields=['published_revision', 'status'], name='cbt_attempt_publish_f4587e_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptgrant',
            index=models.Index(fields=['valid_until'], name='cbt_attempt_valid_u_e6de79_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptgrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__lt', models.F('valid_until'))), name='attempt_grant_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='attemptgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'exam', 'published_revision'), name='unique_active_attempt_grant'),
        ),
        migrations.AddConstraint(
            model_name='cbtexam',
            constraint=models.CheckConstraint(condition=models.Q(('available_from__isnull', True), ('available_until__isnull', True), ('available_from__lt', models.F('available_until')), _connector='OR'), name='cbt_exam_valid_availability_interval'),
        ),
    ]
