# Generated by Django 5.2.11 on 2026-09-01 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_curriculumassignment'),
        ('cbt', '0005_cbtexam_attempt_expiry_policy_cbtexam_available_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineExamPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('presentation_seed', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('package_hash', models.CharField(blank=True, max_length=64)),
                ('package_signature', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('first_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveBigIntegerField(default=0)),
                ('attempt_grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offline_package', to='cbt.attemptgrant')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_packages', to='cbt.cbtexam')),
                ('published_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_packages', to='cbt.publishedexamrevision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_offline_packages', to='academic.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'exam'], name='cbt_offline_student_036112_idx'), models.Index(fields=['published_revision'], name='cbt_offline_publish_afe1c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'attempt_grant', 'published_revision'), name='unique_offline_package_binding')],
            },
        ),
    ]
