# Generated by Django 5.2.11 on 2026-08-22 11:15

import django.db.models.deletion
import django.utils.timezone
import decimal
import idcards.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0010_staff_identity_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('holder_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], db_index=True, max_length=10)),
                ('width_mm', models.DecimalField(decimal_places=2, default=decimal.Decimal('85.60'), max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, default=decimal.Decimal('53.98'), max_digits=6)),
                ('front_layout', models.JSONField(default=idcards.models.empty_layout)),
                ('back_layout', models.JSONField(default=idcards.models.empty_layout)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['holder_type', 'is_active'], name='idcards_idc_holder__7060c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'holder_type'), name='unique_idcard_template_name_holder'), models.CheckConstraint(condition=models.Q(('width_mm__gt', 0)), name='idcard_template_width_positive'), models.CheckConstraint(condition=models.Q(('height_mm__gt', 0)), name='idcard_template_height_positive')],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=10)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_id_cards', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='academic.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='academic.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_cards', to='idcards.idcardtemplate')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
                'indexes': [models.Index(fields=['student', 'status'], name='idcards_idc_student_968ad7_idx'), models.Index(fields=['staff', 'status'], name='idcards_idc_staff_i_fc6a0d_idx'), models.Index(fields=['template', 'status'], name='idcards_idc_templat_8c8474_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('student__isnull', False)), models.Q(('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='idcard_exactly_one_holder')],
            },
        ),
    ]
