# Generated by Django 5.2.11 on 2026-08-22 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('uid_last_four', models.CharField(editable=False, max_length=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('LOST', 'Lost'), ('REPLACED', 'Replaced')], db_index=True, default='ACTIVE', max_length=10)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_credentials', to='idcards.idcard')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_rfid_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_at', '-id'),
                'indexes': [models.Index(fields=['id_card', 'status'], name='idcards_rfi_id_card_ce7df4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('id_card',), name='one_active_rfid_per_idcard')],
            },
        ),
    ]
