# Generated by Django 5.2.11 on 2026-08-25 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idcards", "0004_template_versioning_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDCardDesignAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("BACKGROUND", "Background"),
                            ("WATERMARK", "Watermark"),
                            ("DECORATIVE_GRAPHIC", "Decorative Graphic"),
                        ],
                        db_index=True,
                        default="IMAGE",
                        max_length=25,
                    ),
                ),
                ("file", models.ImageField(upload_to="idcard_assets/")),
                ("mime_type", models.CharField(max_length=50)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_idcard_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["asset_type", "is_active"],
                        name="idcards_idc_asset_t_df8a27_idx",
                    )
                ],
            },
        ),
    ]
