# Generated by Django 5.2.11 on 2026-08-25 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idcards", "0005_idcarddesignasset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizedSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label, e.g. 'Principal Signature'",
                        max_length=120,
                    ),
                ),
                (
                    "signatory_name",
                    models.CharField(
                        help_text="Official name of signatory, e.g. 'Mrs. Amina Yusuf'",
                        max_length=120,
                    ),
                ),
                (
                    "signatory_title",
                    models.CharField(
                        help_text="Signatory designation, e.g. 'Principal'",
                        max_length=120,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_authorized_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AuthorizedSignatureVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="idcard_signatures/")),
                ("mime_type", models.CharField(max_length=50)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="idcards.authorizedsignature",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_signature_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version_number", "-id"),
            },
        ),
        migrations.AddField(
            model_name="authorizedsignature",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_signatures",
                to="idcards.authorizedsignatureversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizedsignatureversion",
            constraint=models.UniqueConstraint(
                fields=("signature", "version_number"),
                name="unique_signature_version_number",
            ),
        ),
        migrations.AddIndex(
            model_name="authorizedsignature",
            index=models.Index(
                fields=["is_active"], name="idcards_aut_is_acti_8ccb20_idx"
            ),
        ),
    ]
