# Generated by Django 5.2.11 on 2026-08-25 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_expand_admission_number_lengths'),
        ('idcards', '0006_authorizedsignature_authorizedsignatureversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('holder_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], db_index=True, max_length=10)),
                ('scope_type', models.CharField(choices=[('DEFAULT', 'Default'), ('SECTION', 'School section'), ('GRADE_LEVEL', 'Grade level'), ('CLASSROOM', 'Classroom'), ('DEPARTMENT', 'Department'), ('STAFF_ROLE', 'Staff role')], db_index=True, max_length=20)),
                ('staff_role', models.CharField(blank=True, choices=[('TEACHER', 'Teacher'), ('ADMINISTRATOR', 'Administrator'), ('ACCOUNTANT', 'Accountant'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_idcard_template_assignments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.gradelevel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.schoolsection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='idcards.idcardtemplate')),
            ],
            options={
                'ordering': ('holder_type', 'scope_type', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'DEFAULT')), fields=('holder_type',), name='one_active_idcard_default_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'CLASSROOM')), fields=('classroom',), name='one_active_idcard_classroom_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'GRADE_LEVEL')), fields=('grade_level',), name='one_active_idcard_grade_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'SECTION')), fields=('section',), name='one_active_idcard_section_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'DEPARTMENT')), fields=('department',), name='one_active_idcard_department_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'STAFF_ROLE')), fields=('staff_role',), name='one_active_idcard_staff_role_assignment')],
            },
        ),
    ]
