# Generated by Django 5.1 on 2025-12-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0007_alter_studentclassenrollment_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('attendance', 'Attendance Alert'), ('fee', 'Fee Reminder'), ('result', 'Result Published'), ('exam', 'Upcoming Exam'), ('event', 'School Event'), ('promotion', 'Promotion Decision'), ('report_card', 'Report Card Available'), ('assignment', 'Assignment Notification'), ('general', 'General Announcement')], max_length=20, unique=True)),
                ('email_subject_template', models.CharField(help_text='Email subject with variables like {{student_name}}', max_length=200)),
                ('email_body_template', models.TextField(help_text='Email body with variables')),
                ('sms_template', models.CharField(help_text='SMS message (max 160 chars) with variables', max_length=160)),
                ('title_template', models.CharField(help_text='Notification title with variables', max_length=200)),
                ('message_template', models.TextField(help_text='Notification message with variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('email_attendance', models.BooleanField(default=True, help_text='Email for attendance alerts')),
                ('email_fees', models.BooleanField(default=True, help_text='Email for fee reminders')),
                ('email_results', models.BooleanField(default=True, help_text='Email when results are published')),
                ('email_exams', models.BooleanField(default=True, help_text='Email for upcoming exams')),
                ('email_events', models.BooleanField(default=True, help_text='Email for school events')),
                ('email_promotions', models.BooleanField(default=True, help_text='Email for promotion decisions')),
                ('email_report_cards', models.BooleanField(default=True, help_text='Email when report cards are ready')),
                ('email_assignments', models.BooleanField(default=True, help_text='Email for assignment notifications (Phase 1.6)')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('sms_attendance', models.BooleanField(default=False, help_text='SMS for attendance alerts')),
                ('sms_fees', models.BooleanField(default=True, help_text='SMS for fee reminders')),
                ('sms_results', models.BooleanField(default=False, help_text='SMS when results are published')),
                ('sms_urgent_only', models.BooleanField(default=True, help_text='Only send SMS for urgent notifications')),
                ('daily_digest', models.BooleanField(default=False, help_text='Receive daily digest email instead of individual emails')),
                ('digest_time', models.TimeField(default='18:00:00', help_text='Time to send daily digest (default 6 PM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance Alert'), ('fee', 'Fee Reminder'), ('result', 'Result Published'), ('exam', 'Upcoming Exam'), ('event', 'School Event'), ('promotion', 'Promotion Decision'), ('report_card', 'Report Card Available'), ('assignment', 'Assignment Notification'), ('general', 'General Announcement')], help_text='Type of notification', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(help_text='Notification title/subject', max_length=200)),
                ('message', models.TextField(help_text='Full notification message')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('sent_via_email', models.BooleanField(default=False, help_text='Whether email was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, help_text='Email delivery error message if any')),
                ('sent_via_sms', models.BooleanField(default=False, help_text='Whether SMS was sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_error', models.TextField(blank=True, help_text='SMS delivery error message if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires (optional)', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, help_text='Student this notification is about (for parents)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academic.student')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
