# Generated by Django 5.2.11 on 2026-07-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_allocatedsubject_term"),
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("result", "Result Published"),
                    ("exam", "Upcoming Exam"),
                    ("event", "School Event"),
                    ("promotion", "Promotion Decision"),
                    ("report_card", "Report Card Available"),
                    ("assignment", "Assignment Notification"),
                    ("direct_message", "Direct Message"),
                    ("general", "General Announcement"),
                ],
                help_text="Type of notification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("result", "Result Published"),
                    ("exam", "Upcoming Exam"),
                    ("event", "School Event"),
                    ("promotion", "Promotion Decision"),
                    ("report_card", "Report Card Available"),
                    ("assignment", "Assignment Notification"),
                    ("direct_message", "Direct Message"),
                    ("general", "General Announcement"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="For message threading",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notifications.directmessage",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional context: the student this message relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_messages",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direct Message",
                "verbose_name_plural": "Direct Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_046ef4_idx",
                    ),
                    models.Index(
                        fields=["sender", "recipient"],
                        name="notificatio_sender__7f357b_idx",
                    ),
                ],
            },
        ),
    ]
