# Generated by Django 5.2.11 on 2026-07-21 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0003_initial"),
        ("administration", "0002_initial"),
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_student_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_attendance_records",
                to="attendance.attendancestatus",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="administration.term",
            ),
        ),
        migrations.AddField(
            model_name="teachersattendance",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.attendancestatus",
            ),
        ),
        migrations.AddField(
            model_name="teachersattendance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodattendance",
            unique_together={("student", "date", "period")},
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["date", "ClassRoom"], name="attendance__date_012cbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["student", "date"], name="attendance__student_0335ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["term", "status"], name="attendance__term_id_f3810f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="teachersattendance",
            unique_together={("teacher", "date", "status")},
        ),
    ]
