# Generated by Django 5.2.11 on 2026-07-14 10:08

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_alter_student_admission_date"),
        ("administration", "0003_alter_term_options_alter_term_unique_together"),
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_student_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="administration.term",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="ClassRoom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academic.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_attendance_records",
                to="attendance.attendancestatus",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academic.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "date")},
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["date", "ClassRoom"], name="attendance__date_012cbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["student", "date"], name="attendance__student_0335ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["term", "status"], name="attendance__term_id_f3810f_idx"
            ),
        ),
    ]
