# Generated by Django 5.2.11 on 2026-08-22 10:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_unambiguous_teacher_attendance(apps, schema_editor):
    TeachersAttendance = apps.get_model('attendance', 'TeachersAttendance')
    StaffAttendance = apps.get_model('attendance', 'StaffAttendance')

    duplicate_keys = set(
        TeachersAttendance.objects.exclude(date__isnull=True)
        .values('teacher_id', 'date')
        .annotate(row_count=models.Count('id'))
        .filter(row_count__gt=1)
        .values_list('teacher_id', 'date')
    )

    rows = TeachersAttendance.objects.select_related('teacher__staff').exclude(
        date__isnull=True
    ).exclude(status__isnull=True)
    for row in rows.iterator():
        if (row.teacher_id, row.date) in duplicate_keys or not row.teacher.staff_id:
            continue
        StaffAttendance.objects.get_or_create(
            staff_id=row.teacher.staff_id,
            date=row.date,
            defaults={
                'status_id': row.status_id,
                'time_in': row.time_in,
                'time_out': row.time_out,
                'notes': row.notes,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_staff_identity_foundation'),
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('device_attendance_enabled', models.BooleanField(default=False)),
                ('student_late_after', models.TimeField(blank=True, null=True)),
                ('staff_late_after', models.TimeField(blank=True, null=True)),
                ('student_close_time', models.TimeField(blank=True, null=True)),
                ('staff_close_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance policies',
            },
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('RFID', 'RFID'), ('SYSTEM', 'System'), ('IMPORT', 'Import')], max_length=20)),
                ('event_type', models.CharField(choices=[('MARKED_PRESENT', 'Marked present'), ('MARKED_ABSENT', 'Marked absent'), ('MARKED_LATE', 'Marked late'), ('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('STATUS_CHANGED', 'Status changed'), ('MANUAL_CORRECTION', 'Manual correction')], max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_attendance_events', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='academic.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='academic.student')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['occurred_at', 'source'], name='attendance__occurre_e8d727_idx'), models.Index(fields=['student', 'occurred_at'], name='attendance__student_62173a_idx'), models.Index(fields=['staff', 'occurred_at'], name='attendance__staff_i_436f97_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('student__isnull', False)), models.Q(('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='attendance_event_exactly_one_subject')],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.staff')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_attendance_records', to='attendance.attendancestatus')),
            ],
            options={
                'ordering': ('-date', 'staff'),
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_7a64db_idx'), models.Index(fields=['staff', 'date'], name='attendance__staff_i_d77b2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_daily_attendance')],
            },
        ),
        migrations.RunPython(copy_unambiguous_teacher_attendance, migrations.RunPython.noop),
    ]
