# Generated by Django 5.2.11 on 2026-08-22 10:36

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_staff_identity_foundation'),
        ('administration', '0002_initial'),
        ('attendance', '0003_attendance_service_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('times_late', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('SSYNC', 'SSync daily attendance'), ('MANUAL', 'Manual'), ('IMPORTED', 'Imported')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_term_attendance_summaries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_attendance_summaries', to='academic.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_summaries', to='administration.term')),
            ],
            options={
                'ordering': ('-term__start_date', 'student__admission_number'),
                'indexes': [models.Index(fields=['term', 'source'], name='attendance__term_id_4f0e9d_idx'), models.Index(fields=['student', 'term'], name='attendance__student_52ba3a_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'term'), name='unique_student_term_attendance_summary'), models.CheckConstraint(condition=models.Q(('days_present__lte', models.F('school_days'))), name='summary_present_lte_school_days'), models.CheckConstraint(condition=models.Q(('days_absent__lte', models.F('school_days'))), name='summary_absent_lte_school_days'), models.CheckConstraint(condition=models.Q(('days_present__lte', django.db.models.expressions.CombinedExpression(models.F('school_days'), '-', models.F('days_absent')))), name='summary_classified_days_lte_school_days')],
            },
        ),
    ]
