# Generated by Django 5.2.11 on 2026-08-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_term_attendance_summary'),
        ('idcards', '0002_rfidcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='device_duplicate_window_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('BIDIRECTIONAL', 'Bidirectional')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('secret_hash', models.CharField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'mode'], name='attendance__is_acti_85ac9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_uid', models.CharField(max_length=64)),
                ('request_id', models.CharField(max_length=64)),
                ('scanned_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(blank=True, choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=10)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('UNKNOWN_CARD', 'Unknown card'), ('REVOKED_CREDENTIAL', 'Revoked credential'), ('INACTIVE_CARD', 'Inactive card'), ('EXPIRED_CARD', 'Expired card'), ('INACTIVE_HOLDER', 'Inactive holder'), ('INACTIVE_DEVICE', 'Inactive device'), ('RFID_DISABLED', 'RFID disabled'), ('DUPLICATE', 'Duplicate'), ('INVALID_DIRECTION', 'Invalid direction'), ('INVALID_TIMESTAMP', 'Invalid timestamp'), ('ERROR', 'Error')], db_index=True, default='ERROR', max_length=24)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='idcards.rfidcredential')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='attendance.attendancedevice')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['device', 'scanned_at'], name='attendance__device__406077_idx'), models.Index(fields=['result', 'scanned_at'], name='attendance__result_4797d4_idx'), models.Index(fields=['credential', 'scanned_at'], name='attendance__credent_b6492e_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'request_id'), name='unique_device_scan_request')],
            },
        ),
    ]
