# Generated by Django 5.2.11 on 2026-08-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancepolicy_device_duplicate_window_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='health_alert_state',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='raw_scan_retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Raw scan retention. Blank disables automatic cleanup.', null=True),
        ),
        migrations.CreateModel(
            name='DeviceSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INVALID_SECRET', 'Invalid device secret'), ('INVALID_SIGNATURE', 'Invalid request signature'), ('REPLAY_ATTEMPT', 'Replay attempt'), ('RATE_LIMIT', 'Rate limit exceeded'), ('DISABLED_DEVICE', 'Disabled device activity'), ('DEVICE_STALE', 'Device stale'), ('DEVICE_OFFLINE', 'Device offline')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_occurred_at', models.DateTimeField(auto_now_add=True)),
                ('last_occurred_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to='attendance.attendancedevice')),
            ],
            options={
                'ordering': ('-last_occurred_at', '-id'),
                'indexes': [models.Index(fields=['device', 'last_occurred_at'], name='attendance__device__30afa3_idx'), models.Index(fields=['event_type', 'last_occurred_at'], name='attendance__event_t_b58351_idx')],
            },
        ),
    ]
